### ISSUE TITLE
RPGLE linter 

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#1]
Linter would be cool. Was thinking the options could be defined in a .json file somewhere, whether a source file or in the IFS.

Some potential settings:

* QualifiedCheck - When true, will warn about structs defined without the qualified keyword.
* PrototypeCheck - When true, will warn about prototypes defined without extpgm or extproc.
* TooMuchHardCoding - When true, will warn about string and numeric constants that have been used in more than one place.
* UpperCaseSpecials - When true, will warn about all special constants that are not uppercase.
* BlankStructNamesCheck - When true, will warn about structs that are defined with a name of *N (no name).
* UseBlankSpecial - When true, will warn when '' is used and will suggest to use *BLANK instead.
* ForceOptionalParens - When true, will warn when conditional operations are used without parentheses
* PointOutUseless - When true, will point out variables, structs and prototypes that are not used.
* NoOCCURS - When true, will warn when the OCCURS keyword is used on definitions
* NoCTDATA - When true, will warn when the CTDATA keyword is used on definitions
* UselessOperationCheck - When true, will warn when when EVAL or CALLP is used
* NoSELECTAll - When true, will warn when SELECT * is used in an embedded SQL statement
* CanConvertSubroutines - When true, subroutines are used and procedures are not, will check to see if a subroutine could become a procedure

**Comment by priceaj** [comment]
fair enough, I take it it will be depenedent on the current extension?

**Comment by worksofliam** [comment]
@priceaj Yes. Although that is only because it depends on include statements that point to source members and stream files. In the future, we'll make it work with local sources too - and therefore not depending on the extension.
