### ISSUE TITLE
IncorrectVariableCase fails to parse SQL with RPG comments correctly replacing wrong portion of SQL

### ISSUE THREAD

**Issue by Wright400** [halcyon-tech/vscode-rpgle#100]
# Issue:
When an RPG free-form comment with `//` is inside an `exec sql` code block the parser for IncorrectVariableCase selects the wrong text to replace. 

The length of the comment affects the offset negatively. The longer the comment the further back the problem underline and auto-fix replacement moves.

Running `RPGLE: Fix all auto-fixable Problems` results in a condition where vscode is stuck until you manually fix the variable it's attempting to auto-fix or until you close vscode.

# Steps to Recreate
Sample SQLRPGLE program
```rpgle
**free

dcl-s sFirstName char(10);
dcl-s sEmpNo char(6);

Exec Sql
  // Break The Parser
  Select
    empno
  Into
    :sEmpNo
  From
    sample.employee
  Where
    firstnme = :SFIRSTNAME;

return;
```

rpglint.json
```json
{
  "IncorrectVariableCase": true
}
```

### After running Auto-Fix on sample program
`Where\n    ` was replaced with `sFirstName`
```sqlrpgle
**free

dcl-s sFirstName char(10);
dcl-s sEmpNo char(6);

Exec Sql
  // Break The Parser
  Select
    empno
  Into
    :sEmpNo
  From
    sample.employee
  sFirstNamefirstnme = :SFIRSTNAME;

return;
```

# Expected Behavior
```sqlrpgle
**free

dcl-s sFirstName char(10);
dcl-s sEmpNo char(6);

Exec Sql
  // Break The Parser
  Select
    empno
  Into
    :sEmpNo
  From
    sample.employee
  Where
    firstnme = :sFirstName;

return;
```

# Workarounds
* Disable IncorrectVariableCase
* Change `//` to `--` before auto-fixing

**Comment by worksofliam** [comment]
Great find. Working on this now.

**Comment by worksofliam** [comment]
Got it working and created a new unit test for it. Will push out a fix soon.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/3708366/180909113-16faa496-0656-4664-a3b8-6729a2da5511.png">

**Comment by worksofliam** [comment]
@Wright400 0.7.5 being released as I write this. Restart VS Code in 5/10 minutes and give it a whirl. You can also see I created a unit test for it in the commit attached.

**Comment by Wright400** [comment]
@worksofliam took a bit longer. I felt like a certain someone giving a demo refreshing vscode waiting for the new version to drop.

Fix works great. Tested in the real program I came across that had a lot of comments in the SQL and auto-fix didn't have any issues.

**Comment by worksofliam** [comment]
@Wright400 So neat! Very glad to read this :)
