### ISSUE TITLE
RPG Lint reports errors when other member type tab or other view active

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#104]
I have noticed this with the output view active and now recently when I have DSPF edit tabs.  The RPG linter marks most of the RPG code of the member tab to the left or right of the DSPF.  It seems the linter in RPG is activated when the DSPF preview is opened. 

The errors that arise are indentation errors because the DSPF is set to a 5-space indent and my RPG is 2 spaces. 

If I get the error below, I no longer receive error of any kind.

```
Error linting /WIASP/[user]/QRPGSRC/PRP04VRG.SQLRPGLE: Cannot read properties of undefined (reading 'options')
TypeError: Cannot read properties of undefined (reading 'options')
	at e.refreshDiagnostics (c:\Users\[user]\.vscode\extensions\halcyontechltd.vscode-rpgle-0.8.0\dist\extension.js:1:58589)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by worksofliam** [comment]
If you could provide a screenshot, that'd great, though I think I know how to recreate the issue.

**Comment by m-tyler** [comment]
Getting the linter to consistently reproduce is a little harder than I expect but I will attempt to grab screen captures today.

**Comment by m-tyler** [comment]
I hope this helps.  the image is large.
![image](https://user-images.githubusercontent.com/1353665/181830726-436b52b4-3fe6-4550-990c-1fda19b895bf.png)

I noticed the error message appear when I open the DSPF preview.  I have seen that message (with different members) being recorded even when that member is not open current but had been. 

I am having trouble getting it to behave badly so I can capture screen images.

**Comment by m-tyler** [comment]
This shows that the linter marks source in error when viewing the output, sometimes.
![image](https://user-images.githubusercontent.com/1353665/181832631-e245a34c-957b-48da-99f1-96402793b6a6.png)

This is more annoying than a real problem so don't spend a lot of time on this.  I was wondering if its a setting or setup of my environment that might be causing this to happen.

**Comment by worksofliam** [comment]
@m-tyler After reading your comments, it seems like the only error is that errors are appearing in the login when you open a display file preview. I understand the issue title now. Let me look into this for you.

**Comment by m-tyler** [comment]
Sorry for the delay getting back, you can treat it as a low pty if you haven't started yet.

**Comment by m-tyler** [comment]
I am adding this here as it may cause this to be a higher priority than I thought.  Whenever I get the lint paring error shown above, the server jobs stop responding or the VS Code side drops the connection, the end result is that I end up canceling server-side SSH jobs when I get that error. 

![image](https://user-images.githubusercontent.com/1353665/184437223-ac21163d-9829-4f25-be05-aa18d433b494.png)

These are just from today.  I have been wondering if its another process in the extensions but through looking at the job activity and errors I get in the VS Code logs, I can only see the error shown from the linter appear and also those jobs still active.

**Comment by worksofliam** [comment]
@m-tyler I am going to need some very specific steps to recreate this issue, please

**Comment by m-tyler** [comment]
If you are asking for steps on how to reproduce the situation where SSH server jobs remain active, I don't think I cannot give that to you.  I only occasionally monitor that subsystem then I find those job remaining.  I know they are part of this extension as this is the only tool I use that uses SSH for its server connection type.  

I am assuming that its related to the lint error I initially reported because I look for that error whenever I don't see the lint process trigger problems or the outline no longer populates.  When I see that lint error in the `RPGLE Language Tools` output view I then go over to the system and look in that subsystem for those jobs.

**Comment by worksofliam** [comment]
@m-tyler What is the status here? What is something I can do to recreate this issue?

**Comment by m-tyler** [comment]
I would like to wait this week to see if I can spot a pattern I can repeat.  But I only see the remaining active SSH server jobs when I notice that the outline and CA are not functioning. 

By this Friday, if I don't have anything more I will close this issue.

**Comment by m-tyler** [comment]
I'm closing this because I cannot figure out how to demonstrate this for you.
