### ISSUE TITLE
IncorrectVariableCase - Changing case in SQL for non-host variables and losing position

### ISSUE THREAD

**Issue by Wright4i** [halcyon-tech/vscode-rpgle#113]
# Issue 1
IncorrectVariableCase is matching on `null` because in our copybook we have `NULL` defined.

This probably shouldn't match at all since null isn't a host variable.

_Note: it doesn't have to be null. You could define BONUS in the example and it'll incorrectly match_

# Issue 2
When replacing `null` to `NULL` it loses position moving left and locks up VS code.

This only occurs when there are blank lines in the SQL between the variables being replaced

# Sample program to recreate issue
```rpgle
**free

dcl-s NULL pointer inz(*NULL);
dcl-s amount1 packed(7:2);
dcl-s amount2 packed(7:2);
dcl-s amount3 packed(7:2);
dcl-s amount4 packed(7:2);
dcl-s amount5 packed(7:2);

// Watch null move left
Exec Sql
  select
    max(case when bonus < 900 then bonus else null end),

    max(case when bonus < 800 then bonus else null end),

    max(case when bonus < 700 then bonus else null end),

    max(case when bonus < 600 then bonus else null end),

    max(case when bonus < 500 then bonus else null end)
  into
    :amount1,:amount2,:amount3,:amount4,:amount5
  from
    sample.employee;
```

# Incorrect result after auto-fixing all fixable problems
```rpgle
**free

dcl-s NULL pointer inz(*NULL);
dcl-s amount1 packed(7:2);
dcl-s amount2 packed(7:2);
dcl-s amount3 packed(7:2);
dcl-s amount4 packed(7:2);
dcl-s amount5 packed(7:2);

// Watch null move left
Exec Sql
  select
    max(case when bonus < 900 then bonus else NULL end),

    max(case when bonus < 800 then bonus elsNULLll end),

    max(case when bonus < 700 then bonus eNULLnull end),

    max(case when bonus < 600 then bonusNULLe null end),
    
    max(case when bonus < 500 thenNULLus else null end)
  into
    :amount1,:amount2,:amount3,:amount4,:amount5
  from
    sample.employee;
```

**Comment by worksofliam** [comment]
We should really only be looking at words that are part of host variables. Good find. I will make a fix.

Also looks like we have some range issues going on here.

**Comment by worksofliam** [comment]
Note to self: it's to do with empty lines.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3708366/184442498-0751e492-a726-4cc5-ae8c-2bd96bd0b70a.png">

**Comment by worksofliam** [comment]
Well, I fixed one bug! 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/3708366/184443521-8930c33d-e918-4aee-861e-82a3227598b0.png">

**Comment by worksofliam** [comment]
The change to get the variable casing to only work for host variables in embedded SQL is going to take a bit of work, but I would say the more serious issue has been tackled. Good find @Wright4i!

**Comment by Wright4i** [comment]
Agreed. We can live with SQL words randomly being capitalized. 

The other issue locking up VS code and breaking compiles was way more serious.

**Comment by Wright4i** [comment]
Oh and thanks!!! @worksofliam

**Comment by worksofliam** [comment]
Woop! 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/3708366/184463687-308d67c9-43c0-40d4-a443-88cabf764cfb.png">

Two new unit tests written for this issue too. I like that.

**Comment by worksofliam** [comment]
I am going to release this tonight.
