### ISSUE TITLE
UselessOperationCheck - Can't handle callp with extender

### ISSUE THREAD

**Issue by Wright4i** [halcyon-tech/vscode-rpgle#114]
# Issue
`callp(e)` is replaced with `e)`

# Sample program
```rpgle
**free
callp(e) test(1:2:3);
```

# Incorrect auto-fix
```rpgle
**free
e) test(1:2:3);
```

# Thoughts
I know callp is useless, but I think in free-form callp(e) or any extender still has some use. I don't really know cause I hardly use callp(e). I think it sets on %error()? 

[**Research supporting that thought:** 
](https://www.ibm.com/docs/en/rdfi/9.6.0?topic=codes-callp-call-prototyped-procedure-program
)"On a free-form calculation specification, the operation code name may be omitted if no extenders are needed, and if the prototype does not have the same name as an operation code."

Either way UselessOperatorCheck definitely shouldn't just leave it as `e)`. Either remove it entirely if I'm wrong or leave it as-is.

**Comment by worksofliam** [comment]
Good find. I will create a fix soon.

**Comment by worksofliam** [comment]
Releasing tonight.
