### ISSUE TITLE
Lint option: Stick to a consistant way of referencing other source (COPY or INCLUDE)

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/vscode-rpgle#12]
I would normally say that /COPY is better because it is included by default when compiling SQLRPGLE without having to compile at *LVL2 however I did notice that IBM state this:

https://www.ibm.com/docs/en/i/7.1?topic=directives-copy-include

>/COPY members are considered fixed-form by default, even if the /COPY directive is coded within a free-form group. If the /COPY member will contain free-form specifications, these must be delimited with /FREE and /END-FREE directives.

so INCLUDE does have it's advantages!

Could we have an option i.e. COPY or INCLUDE to make the behaviour consistant?

**Comment by worksofliam** [comment]
I like this one.

Basically we need an option that says only `include` or only `copy`.

**Comment by bmorris1** [comment]
/INCLUDE members are also considered fixed-form by default. Although now that /FREE isn't used any more, it's about whether the file is **FREE.

The only difference between /INCLUDE and /COPY is whether the precompiler processes it by default. When the RPG docs talk about /COPY in general, they mean both /INCLUDE and /COPY.

But I like the idea of having a lint option to make it consistent.
