### ISSUE TITLE
File name parser is grabbing internal array data

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#120]
I am getting this error in a program that has a compile time array.  
The program is a free format `NOT-**FREE`.  

Original log entry:
```system  "DSPFFD FILE(*LIBL/IT      BE) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RIT 243589)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPD0048:  List of values not valid for parameter FILE.\nCPD0048:  List of values not valid for parameter OUTFILE.\nCPF0001:  Error found on DSPFFD command."
}
```
![image](https://user-images.githubusercontent.com/1353665/188229672-3121058d-0f1a-40f5-9ead-2e922bd563fc.png)

Modified source showing that the compile time array line is the source of the log entry:
```
system  "DSPFFD FILE(*LIBL/ITT     BE) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RITT001851)"; if [[ $? -ne 0 ]]; then exit 1; fi
```
![image](https://user-images.githubusercontent.com/1353665/188228247-fcd610e4-b968-4933-b160-f0df380dabc2.png)

I don't know if this is causing any issues with the outline and other reference stuff gathered from the IBM i, but if not then it would be a low PTY for me.

**Comment by worksofliam** [comment]
Great find. I will look into this a bit later.

**Comment by worksofliam** [comment]
@m-tyler Any chance you can paste some or all of your CTDATA so I can use it for my test case?

**Comment by m-tyler** [comment]
Definition
DCL-S TP CHAR(1) DIM(6) CTDATA PERRCD(1); // Deduction types
       DCL-S TD CHAR(20) DIM(6) ALT(TP);

Array space
**    TP and TD - Deduction types and descriptions
BBenefit      Benefit
DDeferred CompDef Cmp
CChild supportCh Sup
GGarnishment  Garnish
SStatutory    Statut.
VVoluntary    Volntry

**Comment by m-tyler** [comment]
I was able to get the issue to appear with this sample program.
```
       DCL-F QSYSPRT PRINTER(132) USAGE(*OUTPUT) OFLIND(*INOF);
 
       DCL-S OVR_FILE CHAR(21);

       DCL-S TP CHAR(1) DIM(6) CTDATA PERRCD(1);                                // Deduction types
       DCL-S TD CHAR(20) DIM(6) ALT(TP);

       *INLR = *ON;
       Return;

**    TP and TD - Deduction types and descriptions
BBenefit      Benefit
DDeferred CompDef Cmp
CChild supportCh Sup
GGarnishment  Garnish
SStatutory    Statut.
VVoluntary    Volntry
```

**Comment by worksofliam** [comment]
@m-tyler I will be putting the fix in today.

**Comment by worksofliam** [comment]
@m-tyler Out in 0.10.3!!

**Comment by m-tyler** [comment]
Installed and its fixed for me!

Thanks.
