### ISSUE TITLE
COPY/INCLUDE doesn't handle library list

### ISSUE THREAD

**Issue by mwmayer4** [halcyon-tech/vscode-rpgle#127]
I've tried a variety of ways to define the /include by specifying the lib/srcfile/mbr, srcfile/mbr and just the member. I have the members in the same QRPGLESRC and the library list and current library set to the library where the source resides. 

The Peek Definition <option F12> on Mac 99% of the time says no definition found. Yesterday, however, at one point the F12 did open a definition. I cannot get it to repeat today. Even when it did open one, there was still no outline for any of the contents.

What's even stranger is that a new issue has started wherein, the editor will only open one member at at time, unless the first member you open has been modified. This began happening when I changed a setting to auto save. I then changed the setting back, but the editor will not open a second member unless the first one has been modified. 

<img width="525" alt="_ 2022-09-13 at 8 36 41 AM" src="https://user-images.githubusercontent.com/109669620/189915884-dd5932ee-b723-4945-abb8-d53d0cd44772.png">

<img width="338" alt="_ 2022-09-13 at 8 36 52 AM" src="https://user-images.githubusercontent.com/109669620/189915997-aeda9e62-16b3-4bbd-aa00-939cb1b1ed6e.png">

IBM i  V7R3
Code for IBM i v1.5.11 9/2/2022 13:43:36
* QCCSID: 37
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/"
  },
  {
    "command": "ls -p /QOpenSys/pkgs/bin/",
    "code": 2,
    "stderr": "/QOpenSys/pkgs/bin/ not found",
    "cwd": "/"
  }
]
```

**Comment by worksofliam** [comment]
> I have the members in the same QRPGLESRC and the library list and current library set to the library where the source resides.
>
>The Peek Definition on Mac 99% of the time says no definition found. Yesterday, however, at one point the F12 did open a definition. I cannot get it to repeat today. Even when it did open one, there was still no outline for any of the contents.

As of right now, Code for IBM i does not use the library list to search for include/copy statements, for example:

```rpgle
**free
// Where BASELIB is the library of the member you're currently editing

// Will search for ABCMBR in BASELIB/QRPGLEREF
/COPY ABCMBR

// Will search for QRPGLEREF,ABCMBR in BASELIB
/COPY QRPGLEREF,ABCMBR

// Will search grab OTHERLIB/QRPGLEREF,AMBR due to absolute path
/COPY OTHERLIB/QRPGLEREF,AMBR
```

Perhaps that is your issue?

Also, the outline view will only show definitions in the source you're currently working in and will not show definitions from copybooks.

**Comment by mwmayer4** [comment]
I was under the impression the outline view would show the definitions (like RDi). So my issue is not really an issue. It sure would be nice if it did show though. Thanks

**Comment by worksofliam** [comment]
> I was under the impression the outline view would show the definitions (like RDi)

It will! But only for items in the active editor 😊

**Comment by worksofliam** [comment]
Will be possible to support this when this PR has been merged: https://github.com/halcyon-tech/vscode-ibmi/pull/1224/files#diff-bdc40b7bbc93e3369a9b963b709ed6bc8d4d9d70db7362e1f14d6edc78c07cd6
