### ISSUE TITLE
RPG Lint error on comment

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#129]
Is the linter for RPG supposed to mark up comments that match a source item like SUBR name or is this because the lint tool is parsing by token only and then matches on those solo tokens?

![image](https://user-images.githubusercontent.com/1353665/192382205-e71ed466-a901-4a5b-b611-827610f4f4d9.png)

Adding //@rpglint-skip does prevent this but that makes the code look a little ugly.

**Comment by worksofliam** [comment]
It's not. If you wouldn't mind sharing a snippet so I recreate that and create a test case for it, that'd be great.

**Comment by m-tyler** [comment]
**FREE 
Exsr Screen;
*INLR = *ON;
Return;
//-----------------------------------------------------------------------
// Screen
//-----------------------------------------------------------------------
Begsr Screen;

  Select;
    When Dspfinfds.FKey = F05 // Refresh/Reload screen
      ;
      Reload = *ON;
  Endsl;

Endsr;
