### ISSUE TITLE
Outline - Cannot read properties of undefined (reading 'toUpperCase')

### ISSUE THREAD

**Issue by krisbaehr** [halcyon-tech/vscode-rpgle#139]
We are checking out Code for IBM i and all you've done for the IBM i and open source and are loving what we are seeing! We use VS Code for Node.js and Angular and would love to be able to program RPG there as well.

### The issue I'm running into trying to build the outline for the following code:
```
       dcl-proc getHandle;

       dcl-pi *n like(handle_t) end-pi;

       dcl-s rcdHandle like(handle_t) inz;

       rcdHandle = %lookup(' ' :handles);
       if (rcdHandle > 0);
         handles(rcdHandle) = 'A';
       endif;

       return rcdHandle;

       end-proc getHandle;
```

### The error received in the RPGLE language tools OUTPUT is:
Error parsing /DUNC/QTSOURCE/A0.SQLRPGLE: Cannot read properties of undefined (reading 'toUpperCase')
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
	at e.expandKeywords (c:\Users\baehk\.vscode\extensions\halcyontechltd.vscode-rpgle-0.12.0\dist\extension.js:1:41799)
	at e.getDocs (c:\Users\baehk\.vscode\extensions\halcyontechltd.vscode-rpgle-0.12.0\dist\extension.js:1:38194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.provideDocumentSymbols (c:\Users\baehk\.vscode\extensions\halcyontechltd.vscode-rpgle-0.12.0\dist\extension.js:1:51710)
	at async n.provideDocumentSymbols (c:\Users\baehk\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:37375)
	
### This code parses fine:
```
       dcl-proc getHandle;

       // split the dcl-pi and end-pi
       dcl-pi *n like(handle_t)
       end-pi;

       dcl-s rcdHandle like(handle_t) inz;

       rcdHandle = %lookup(' ' :handles);
       if (rcdHandle > 0);
         handles(rcdHandle) = 'A';
       endif;

       return rcdHandle;

       end-proc getHandle;
```

### **And so does this:**
```
       dcl-proc getHandle;

       dcl-pi *n like(handle_t) end-pi;

       dcl-s rcdHandle like(handle_t) inz;

       rcdHandle = %lookup(' ' :handles);
       
       // removed unnecessary parens
       if rcdHandle > 0;
         handles(rcdHandle) = 'A';
       endif;

       return rcdHandle;

       end-proc getHandle;
```

**Comment by worksofliam** [comment]
Will look at this ASAP. I just put a fix today which may fix this actually solve this, but you are fab for providing an example.

**Comment by worksofliam** [comment]
Have recreated the issue with a new test case.

**Comment by worksofliam** [comment]
0.12.1 has been released.

@krisbaehr Please let me know what you find! Thanks for a great bug report.

**Comment by krisbaehr** [comment]
@worksofliam I picked up 0.12.1 and tested your changes this morning. Everything is working great. I figured since you spend a bunch of time giving us these fantastic tools, I can do my best to nail down the actual problem and present it in a concise manner. Thanks for the quick response!
