### ISSUE TITLE
Autocomplete window stays active more than usual

### ISSUE THREAD

**Issue by Hadkins2** [halcyon-tech/vscode-rpgle#147]
![image](https://user-images.githubusercontent.com/95584606/198083693-70e7d6f8-40e2-466b-b5f2-e7a69bf150f2.png)

When typing a line of code, I rely on the autocomplete feature, but a recent change has made it start popping up more often.  For example in the line of comments, I typed the // and then space and the autocomplete box popped up.  Is this configurable?  I rely on this for completing variable name and it is especially handy for qualified variables.

Thanks, 
Howard

**Comment by Hadkins2** [comment]
I guess it all boils down to the way I got used to it reacting.  In my mind, space means there is nothing left to try to autocomplete.  I got used to hitting Esc to make it stop in certain situations.  But the way I usually code I will get to the end of the line and press Enter.  If autocomplete is primed to react when I hit Enter, it adds appxClose on a lot of lines and I have to delete that before getting my next line. 

![image](https://user-images.githubusercontent.com/95584606/198088516-6fe12b02-069d-4dd6-bfc5-f8cff3e25d57.png)

 Is it possible to make space being a trigger a configurable option????

**Comment by worksofliam** [comment]
@Hadkins2 I don't think there is a way to make it configurable with the way it works in the backend - though I have no problem removing the space as a trigger.

What do you think?

**Comment by Hadkins2** [comment]
Leave it as it is now.  Looking through the discussions, I don't see anyone else having issues with the current behavior.  This is just something I need to adjust to.

Thanks for responding.

Howard

**Comment by worksofliam** [comment]
@Hadkins2 I really do appreciate this feedback.

vscode-rpgle has a big internal change this week (thus why this is happening) and your feedback is excellent.

Thank you!

**Comment by Hadkins2** [comment]
Looking forward to the updates.  This product just keeps getting better and better.

**Comment by worksofliam** [comment]
Hey @Hadkins2 - sorry to bother you about this.

 I am trying to show my higher ups that our users are active and like to provide feedback like this.

Whenever you get a moment, can you check this out and leave some feedback there? Thanks!

https://github.com/orgs/halcyon-tech/discussions/350

**Comment by Hadkins2** [comment]
Done.  My pleasure to provide feedback
