### ISSUE TITLE
File description doesn't apear with the keyword "TEMPLATE"

### ISSUE THREAD

**Issue by sebCIL** [halcyon-tech/vscode-rpgle#153]
File description doesn't apear with the keyword "TEMPLATE".
![image](https://user-images.githubusercontent.com/18192917/198817548-183a2bbd-4743-4de0-bec9-80c68f0aafa5.png)

**Comment by worksofliam** [comment]
@sebCIL Odd.

Please share that snippet of code so I can create a test case out of it, or feel free to do so yourself
