### ISSUE TITLE
I am receiving crash reports with version 0.14.2

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#156]
![image](https://user-images.githubusercontent.com/1353665/199053650-583351e3-f465-444f-b088-f48ce1959108.png)
 I will restart VS Code and keep an eye out to see if it happens again. 
My log of the error. 
[RPGLE language tools.zip](https://github.com/halcyon-tech/vscode-rpgle/files/9902768/RPGLE.language.tools.zip)

**Comment by worksofliam** [comment]
@m-tyler Please update to 0.15.0 and see if the same issue persists. Thanks.

**Comment by m-tyler** [comment]
I'm looking to see if I can tell how the problem appeared to see if I can replicate it under 0.14.0 before upgrading that way I try the same actions to see if it gets resolved.

**Comment by worksofliam** [comment]
> After upgrading to 0.15.0, no syntax tokenization occurs, the source color is all white.

Check if you have IBM i Languages installed. It is no longer a required dependancy.

Are you developing in source members, IFS, or local workspace?

**Comment by worksofliam** [comment]
@m-tyler I have recreated the issue with `DCL-F`....

**Comment by m-tyler** [comment]
I develop only with QSYS source files.

`IBM i Languages` is installed.

**Comment by worksofliam** [comment]
But you get no highlighting at all when you edit `.rpgle` or `.sqlrpgle`?

**Comment by worksofliam** [comment]
@m-tyler 0.15.1 will include a fix for the `DCL-F` issue.

**Comment by worksofliam** [comment]
@m-tyler Woop!!

Sorry for that issue. As you know, 0.14.0 was a big one and I didn't catch everything. I really appreciate you.

**Comment by m-tyler** [comment]
Oh, thank you for developing this project.
