### ISSUE TITLE
RPGLE language tools rename

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#157]
I propose to change the name of `RPGLE language tools` to `RPGLE`.

It seems like most of the language providers in the VS Code Marketplace have a single word for their extension. Usually it's just the name of the programming language:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/3708366/199282530-491959c9-2883-44e3-83b9-6d6021a36c1c.png">

**Comment by worksofliam** [comment]
@halcyon-tech/core What do you think of this?

**Comment by Wright4i** [comment]
Agreed it should just be `RPGLE`

**Comment by chrjorgensen** [comment]
I also agree 👍

**Comment by worksofliam** [comment]
Done in 0.15.3
