### ISSUE TITLE
RPGLE Language server has issues and stops suddenly

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#159]
Since upgrading to the versions that support the new RPGLE language server, I have been seeing issues with it crashing suddenly or not providing the features of the extension.

Attached is the latest error log I get when I open a particular IBM i share mapped to a windows drive.
[Version 0.15.2 RPGLE server issue.zip](https://github.com/halcyon-tech/vscode-rpgle/files/9921615/Version.0.15.2.RPGLE.server.issue.zip)

If I open VS Code on another IBM i share mapped to a windows drive, I don't get the error. 

If I open VS Code without specifying a working folder I do not see these errors attached. 

I have seen issues exiting VS Code if the RPGLE language server stops suddenly. 
![image](https://user-images.githubusercontent.com/1353665/199526161-0ba94d5f-00a0-4391-9d24-68b9a1458928.png)

If I revert to 0.14.1 I don't see these issues.   

Looking at my mapped drive folders, I looked to see if any .git folder is the cause of the problems but one mapped drive folder I open has a .git repo and VS Code functions just fine.   Removing any .git folders from my mapped drive folder seems to stop the language server from crashing.   I'll have to do more testing with .git in working folders.  I might have set up things wrong.

**Comment by worksofliam** [comment]
So to be clear:

You have a mapped drive setup on your system which points to an IBM i filesystem?

**Comment by m-tyler** [comment]
Correct.  The feature of the mapped drive has been in use by me with this extension since I started using VS Code over a year ago. 
I don't feel mapped drives is the part that is of issue.  I say this because I can use the extension with another mapped drive and I have no issues.  

Would there be any conflict with a folder having a .git repo set up within?  I cleaned up some folders with .git repos and now don't see the issue appear with the language server since.

**Comment by worksofliam** [comment]
No, I think the real issue is a bug in the parser that I believe I've found now.

**Comment by m-tyler** [comment]
Cool!

**Comment by worksofliam** [comment]
Here's the basic of the bug. This is valid behaviour:

There is only one item in the outline for two definitions (this is how it's always worked)

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3708366/199549794-ed160e92-fd2c-43f1-a0e0-108976e9a2ba.png">

Instead, this is what is happening for you (I just stopped it from crashing to show you :))

<img width="858" alt="image" src="https://user-images.githubusercontent.com/3708366/199549992-bcefcd40-120f-4c0e-a6cf-eeede23be228.png">

I need to fix this up and write a test case for it, and then I will put a release out.

**Comment by m-tyler** [comment]
That's good news.

However, the log I sent in the OP, occurred without a source member actually being open.   I had no editors open and I don't think I was even connected to the server at the time.  (The image from above was from an earlier session where I had connected to our server).  

Could the bug occur based on something in the cache?

**Comment by worksofliam** [comment]
@m-tyler Yes, it's quite possible it could have been triggered by an internal cache. 0.15.3 is coming out now. Give it a go for me and let me know if the issue persists. Maybe we will fix two bugs today.

**Comment by worksofliam** [comment]
@m-tyler I will also add this: you're likely seeing a lot more errors in newer release we removed *all* try/catch statements from our code. We're aiming to create better code and better performing code, and that is part of it. So there now some instances showing where we aren't capturing errors (like this one!)

**Comment by m-tyler** [comment]
No, I have not updated it yet.  I am still working on things to get my working folder to a state as close to when I first noticed the issue appear.  

So the issue wasn't just what I sent via the log file.  There were many attempts that no error appeared in the RPGLE Language output view but VS Code wouldn't function well.  When I reverted back to 0.14.1 I did not encounter any problems.

So, might have found a clue.  I moved off a couple of folders from the mapped drive folder to my laptop drive.  VS Code with the extension at 0.15.2 started working fine.  So I decided to move them back. Now I see this with VS Code just done with start-up.

![image](https://user-images.githubusercontent.com/1353665/199575878-511bf2e3-67f0-4d64-81ac-c0f27a937fd1.png)
![image](https://user-images.githubusercontent.com/1353665/199575953-8d277e12-ce46-4420-8008-14fdab6e2dad.png)

Now I am going to update to 0.15.3 with these two folders still in my mapped drive folder and see if the picture error reappears.

**Comment by m-tyler** [comment]
I have updated to 0.15.3 now.  I don't see the properties error anymore (example in prior post).   That error I think came from the existence of a folder with a whole lot of duplicated source.  This source was from my library on my IBM i and I copied it to my IBM i home folder mapped drive.   Once that folder was removed, I no longer saw that error reported. 

A couple of items were the source of the issue I'm my OP.  The folder I mentioned above and then I had another folder with a .git repo set up.  That did not cause any of the initial problems in my OP but my VS Code sessions were quite a bit slower.  I deleted the .git folder and now VS Code seems responsive.

I also cleared my file history cache. 

I think this problem may have been solved. 

Thanks for the help!

**Comment by worksofliam** [comment]
@m-tyler Glad to hear it.

> I deleted the .git folder and now VS Code seems responsive.

You shouldn't have to do this any long. I added in more code to ignore `.git` folders (which it should have been doing anyway, but now I am being explicit about it).

Also, I don't generally recommend using a git repo on a mapped drive due to the slowness it can cause over network. Git is very filesystem heavy, and adding a mapped drive into the mix doesn't sound too good.

**Comment by m-tyler** [comment]
Just an FYI update, ever since I was able to get my environment running again, the outline builds lighting fast compared to how it used to build.  I wonder if some of that was due to me clearing the editor cache in VS Code or is it all part of the latest features?

**Comment by worksofliam** [comment]
@m-tyler that's awesome!

Likely due to the big change in 0.14. I am so glad to hear that!
