### ISSUE TITLE
IASP definition being inserted in place of library in downloadMemberContentWithDates()

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#160]
I defined the IASP name of our system on my connection and it now appears in the create or replace alias SQL command instead of the library.

If I remove the IASP value from the connection setting, shut VS Code, open VS Code, connect to my server, open a member, I still see the IASP reference in the create alias command. 

I have yet to verify if this occurred in prior release.

* Code for IBM I version 1.5.24
* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS ILEDITOR.WIASP_VSCODE_RPGLINT for "WIASP"."VSCODE"("RPGLINT")
{
    "code": 2,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 01522\nNATIVE ERROR CODE: 403\nAlias WIASP_VSCODE_RPGLINT in ILEDITOR created but table or view not found.",
    "stderr": ""
}

/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT LENGTH(srcdta) as LENGTH FROM ILEDITOR.WIASP_VSCODE_RPGLINT limit 1
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nVSCODE in WIASP type *FILE not found.",
    "stderr": ""
}
```
This can be treated as a lower PTY for me as I will be out of the office for a week.

Thanks.

**Comment by worksofliam** [comment]
Happening here: https://github.com/halcyon-tech/vscode-rpgle/blob/83773b479ad2bba25f5dca80534417106f9b4c1b/server/src/server.ts#L121

We are taking account of the ASP in the URI. Working on it now.

**Comment by worksofliam** [comment]
@m-tyler I know you won't be back next week, but 0.15.5 is out which should resolve this issue. Thanks!

**Comment by m-tyler** [comment]
I had a little time this early am, I upgraded to 0.15.5 and tested again with positive results.  Thanks!

**Comment by worksofliam** [comment]
@m-tyler nice! I love early morning fixes. Have a great week whatever you get up to.

**Comment by m-tyler** [comment]
Hi, 
I just updated to 0.15.9 and now I see this in the log.  I was looking over the log I only see WIASP being used for the library for the RPGLINT member.  I don't recall if the RPGLINT member was formatted like this in 0.15.5. 
```
CREATE OR REPLACE ALIAS ILEDITOR.WIASP_VSCODE_RPGLINT for "WIASP"."VSCODE"("RPGLINT")
{
    "code": 2,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 01522\nNATIVE ERROR CODE: 403\nAlias WIASP_VSCODE_RPGLINT in ILEDITOR created but table or view not found.",
    "stderr": ""
}
```

**Comment by worksofliam** [comment]
@m-tyler this is possibly a new bug. Would you mind raising this bug?

**Comment by m-tyler** [comment]
I created issue #167.
