### ISSUE TITLE
Code becomes sluggish when upgrading from v0.14.2 to v0.15.0

### ISSUE THREAD

**Issue by richardm90** [halcyon-tech/vscode-rpgle#166]
I started experiencing a problem with VS Code and I think I've managed to track down the offending extension.

VS Code started becoming really slow and sluggish, everything just took a really long time to complete. After opening VS Code and switching to the Code for IBM i extension it took several minutes for my list of connections to appear. If I then clicked on a connection it took many minutes for the connection to complete and sometimes it failed with a timeout error.

I then tried working through my installed extensions and disabled them one by one to see if the problem would go away, it went away when I disabled the vscode-rpgle extension. Up until recently this had been working fine so I tried installing an older version of the extension and eventually found that it was v0.15.0 that was causing my problem. If I install v0.14.2 then it works fine.

Looking at the changes in v0.15.0 they seem to be related to local development and I'm pretty sure I don't have local development settings configured.

The only extensions I have installed are the IBM i development pack extensions. 

I am running on a Linux desktop. I have other Linux desktops that work just fine with the latest version of the vscode-rpgle extension.

My next steps will be to reinstall VS Code to see if that resolves the issue but before doing so I thought I'd log the issue in case it would helpful to capture any settings that might help isolate the problem.

**Comment by worksofliam** [comment]
@richardm90 let me look into this today and tomorrow and see if I can find something meaningful for it.

**Comment by worksofliam** [comment]
@richardm90 Of course, it is related to 'project mode'. Do you have a local workspace open (e.g. a folder open in VS Code?) when working with source members?

**Comment by richardm90** [comment]
@worksofliam yes, I do have a local folder open

**Comment by richardm90** [comment]
@worksofliam I'm not sure that's the full answer though as I tried the same on another desktop (with an open local folder) and it works OK.

**Comment by worksofliam** [comment]
@richardm90 was the other desktop also Linux or a different OS?

**Comment by richardm90** [comment]
@worksofliam both are linux

**Comment by richardm90** [comment]
@worksofliam if it helps to jump on a screen share then let me know

**Comment by worksofliam** [comment]
@richardm90 send me an email at liam@whoiworkfor.com and we will organise the meeting for later this week.

I'm out of office at a conference until Wednesday.

**Comment by richardm90** [comment]
@worksofliam that email address bounced.

**Comment by worksofliam** [comment]
Sorry: liama@whoiworkfor.com.

**Comment by richardm90** [comment]
@worksofliam still bounced, this is the message I get 

Address not found
Your message wasn't delivered to liama@whoiworkfor.com because the domain [whoiworkfor.com](http://whoiworkfor.com/) couldn't be found. Check for typos or unnecessary spaces and try again.

**Comment by worksofliam** [comment]
Sent you a DM on LinkedIn 😄

**Comment by richardm90** [comment]
Sorry, I was being really dim there!
