### ISSUE TITLE
Content assist should be enabled automatically 

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#17]
Only the linter should be an optional feature since it has a large impact

**Comment by kevindRuby** [comment]
Content Assist does not seem to be working.  tried Shift +12 and have all options in settings ticked

**Comment by worksofliam** [comment]
Hey @kevindRuby -

Would you mind sharing a code snippet of something that doesn't work? 

Thanks!

**Comment by worksofliam** [comment]
@kevindRuby Did some testing again - I can see it working.

![36B70CE2-896B-4725-9D72-40C4E44D89FF](https://user-images.githubusercontent.com/3708366/144727631-b753389a-9f6a-4ef6-b9b1-fb3c6c34e0d7.png)

Liam

**Comment by kevindRuby** [comment]
> @kevindRuby Did some testing again - I can see it working.
> 
> ![36B70CE2-896B-4725-9D72-40C4E44D89FF](https://user-images.githubusercontent.com/3708366/144727631-b753389a-9f6a-4ef6-b9b1-fb3c6c34e0d7.png)
> 
> Liam

See below a screenshot. Shift + F12 does not work here.  Hover also does not work.   I will also added some code:
![image](https://user-images.githubusercontent.com/3673482/144752982-95c11351-1a2d-4732-aa8f-a68a98c4f678.png)




**LIAMALLAN2.RPGLE**
`**FREE

Ctl-opt DFTACTGRP(*NO);

//try again https://youtu.be/b6ZmtTelYDU?list=PLNl31cqBafCp-ml8WqPeriHWLD1bkg7KL
/copy qkdcopybks,kdcopybok1

dcl-s mynum int(10);
mynum = 12;



//call the procedure 1
multiplyBy2(mynum);

//call the procedure 2
sayHello('Jeff');

// printf(mynum);

return;

//define the procedures 1
dcl-proc multiplyBy2;

    dcl-pi *N ;  //one parameter
                //No return value
        mynum2 int(10) const;
    end-pi;

    dsply (2 * mynum2);

    return;
end-proc;


//define the procedures 2
DCL-PROC sayHello;
    DCL-PI *N;
        name CHAR(10) CONST;
    END-PI;

    DSPLY ('Hello ' + name);
END-PROC;
`

**KDCOPYBOK1.RPGLE**
`**Free

dcl-proc printf int(10) ExtProc('printf');
    format Pointer Value Options(*String);
end-proc;

dcl-proc writeJobLog int(10) ExtProc('Qp0zLprintf');
    *n pointer value options(*string);
    *n pointer value options(*string: *nopass);
end-proc;
`

**Comment by worksofliam** [comment]
@kevindRuby Tested and works okay for me.

Can you share a screenshot of your outline view? Also, is `qkdcopybks` in the same library as the base member?

**Comment by kevindRuby** [comment]
No.  Also, is qkdcopybks is in a different library from the base member. 

Can't find the Outline view

**Comment by worksofliam** [comment]
@kevindRuby 

As noted in the [FAQ](https://github.com/halcyon-tech/vscode-rpgle#faq), we only support bringing sources in from the same working library.

The [outline view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) can be found in the Explorer panel, but can be moved to anywhere you like.
