### ISSUE TITLE
Linter rule `NoUnreferenced` set true then *INZSR is marked with warning

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#170]
Is there any way to skip marking *INZSR?
![image](https://user-images.githubusercontent.com/1353665/202533090-44d59fc2-6ab1-4686-a543-17c5fe747dbc.png)

**Comment by worksofliam** [comment]
Ha, good spot. Yes, I will look into this today

**Comment by m-tyler** [comment]
Where does the reference information come from when one has not compiled the code?  I am seeing the markups drifting from the proper source of the linter issue. 

![image](https://user-images.githubusercontent.com/1353665/202549759-69920d77-5a66-4531-a77a-bbede21065bc.png)

The named item of `LDA` is not referenced but all sub fields are.

The field `Move1` is used.

**Comment by worksofliam** [comment]
@m-tyler Could be a bigger issue. 

Share something I can use to recreate that when you have a moment.

**Comment by m-tyler** [comment]
[ISSUE_170.RPGLE.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/10035574/ISSUE_170.RPGLE.TXT)
[ISSUE_170A.RPGLE_DS.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/10035575/ISSUE_170A.RPGLE_DS.TXT)

These two, demo the issue and the code is compilable.

**Comment by worksofliam** [comment]
@m-tyler First issue is fixed. Second one needs a bit of work, so I will keep you posted.

**Comment by m-tyler** [comment]
For internal *ENTRY prototypes, are they supposed to be marked up as not referenced?
This is NOT a `NOMAIN` program.
![image](https://user-images.githubusercontent.com/1353665/202737697-bad57885-89dd-426d-a0d4-2ed1c1428c04.png)

I'm not saying it shouldn't be marked just curious about the rules marking up not referenced items.

**Comment by worksofliam** [comment]
@m-tyler 0.15.13 was released. You should give it a go.

> For internal *ENTRY prototypes, are they supposed to be marked up as not referenced?

Yes, if it's not referenced then you will get the error. You don't need a PR for the program when you have a PI.

Thanks,
Liam

**Comment by m-tyler** [comment]
I confirm that this fix works for me.
![image](https://user-images.githubusercontent.com/1353665/202819169-9aa9e35d-ec73-45f6-8cb7-91c97749d5d8.png)
