### ISSUE TITLE
Fixed form comments not converting to free form comments

### ISSUE THREAD

**Issue by JDubbTX** [halcyon-tech/vscode-rpgle#173]
Perhaps this is up for a debate.

I have been trying out VSCODE in local development and building with BOB, mainly as a learning exercise.  As part of the process I'm taking older RPGLE programs and 1) converting them to free form 2) Adding **FREE at the top 3) reformatting based on linting rules.

One issue I have run across repeatedly is fixed form style comments will break the compile.  These aren't touched by the converter, and seem to confuse the linter.  My manual work arround is to add '// ' at the beginning of each line - manually changing them to free form style.  This allows the linter to work and it will then compile successfully.

Here is an example:

![image](https://user-images.githubusercontent.com/56802156/203311507-c5997f5e-ea9e-4849-ab9d-756e8ec4fb36.png)

**Comment by worksofliam** [comment]
@JDubbTX I think you may have the wrong repo. This repo doesn't deal with any conversion.

You likely want vscode-rpgfree.
