### ISSUE TITLE
Linter rule NoUnreferenced set true then *PSSR is marked with warning

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#175]
See issue #170.

The same needs to be done for *PSSR.

Thanks.

**Comment by worksofliam** [comment]
@m-tyler Any chance you can provide a code sample of this? Thanks!

**Comment by m-tyler** [comment]
[ISSUE_175.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/10104903/ISSUE_175.RPGLE.txt)

FYI, this was with me being at version 0.16.0.  I tried updating to the latest version but I was having some issues so I downgraded.

**Comment by worksofliam** [comment]
Thanks, I will get a test and fix in for this ASAP.

**Comment by worksofliam** [comment]
Ready to be released.

**Comment by worksofliam** [comment]
This just went out!
