### ISSUE TITLE
Hover assist should display definition details for variables, constants, data structures, files, etc. 

### ISSUE THREAD

**Issue by cbuck0222** [halcyon-tech/vscode-rpgle#18]
When browsing and attempting to follow existing code, it would be nice to be able to hover over a variable name, for example, to display definition details about that field and where it is defined (i.e. external definition location, data type, length, etc.). It would also be helpful to offer the external location for file declarations as well. RDi offers this feature and is quite handy, especially for following programs you are not the author of. 

Example:
If I hover over this variable, it should give me the definition details in a tool-tip type of hover box.
![image](https://user-images.githubusercontent.com/86483883/143940450-6d956b48-8976-471f-b193-a118fd3447e6.png)

RDi example:
![image](https://user-images.githubusercontent.com/86483883/143940559-890e5f22-e3b2-4364-aeba-41cc9a722b93.png)

**Comment by worksofliam** [comment]
Depends on #16. Good feature
