### ISSUE TITLE
LInter returning JS error reading property `Line` 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#180]
I am receiving this error in the RPGLE language client output view (so far I only see it with one program).

```
Error linting member:/D2WFIQUAL/QRPGSRC/PRP05ORG.SQLRPGLE: Cannot read properties of undefined (reading 'line')
TypeError: Cannot read properties of undefined (reading 'line')
    at c.getErrors (c:\Users\-------\.vscode\extensions\halcyontechltd.vscode-rpgle-0.16.3\out\server.js:1:244597)
    at m (c:\Users\--------\.vscode\extensions\halcyontechltd.vscode-rpgle-0.16.3\out\server.js:1:16543)
    at async t.default (c:\Users\--------\.vscode\extensions\halcyontechltd.vscode-rpgle-0.16.3\out\server.js:1:13584)
```
Is there a way to set something on to see what source line (in my program source) is causing this as the member causing this error is rather large?

**Comment by worksofliam** [comment]
No way to determine the line with the error (yet!).

**Comment by m-tyler** [comment]
[PRP05ORG.SQLRPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/10187272/PRP05ORG.SQLRPGLE.txt)

This source reproduces the issue for me.

**Comment by worksofliam** [comment]
@m-tyler Please share your lint config here. Thanks!

**Comment by worksofliam** [comment]
Recreated the issue. Fix will be out today.

**Comment by m-tyler** [comment]
{
  "BlankStructNamesCheck": false,
  "QualifiedCheck": false,
  "PrototypeCheck": false,
  "ForceOptionalParens": false,
  "NoOCCURS": false,
  "NoSELECTAll": false,
  "UppercaseConstants": true,
  "IncorrectVariableCase": true,
  "StringLiteralDupe": false,
  "NoSQLJoins": false,
  "NoCTDATA": false,
  "PrettyComments": false,
  "NoGlobalSubroutines": false,
  "NoLocalSubroutines": false,
  "UppercaseDirectives": false,
  "RequiresProcedureDescription": false,
  "UselessOperationCheck": false,
  "NoUnreferenced":true,
  "SpecificCasing": [
    {"operation": "*bif","expected": "*upper"}
  ],
  "indent": 2
}
