### ISSUE TITLE
Lint Option: unused procedures

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/vscode-rpgle#19]
Just noticed the RDi linter checks for unused procedures

we should prob do the same!

**Comment by worksofliam** [comment]
Excellent idea

**Comment by worksofliam** [comment]
Well, this one gets a bit tricky.. because what if it's a service program? Perhaps this should only warn for procedures when they're not used and they're not export procedures.

**Comment by priceaj** [comment]
Yeah that's a good call

**Comment by worksofliam** [comment]
Plan is to add something like this but only check if it's not using `NOMAIN` in the options.

**Comment by priceaj** [comment]
We have standard headers in copy sources depending on which type of program it is. E.g. service program, program

Will the linter be able to see that copy source?

**Comment by worksofliam** [comment]
@priceaj Yes :D The linter is already pulling in included sources into consideration! You can test it with things like 'Go to definition' on a procedure and it should take you to the PR :)

**Comment by worksofliam** [comment]
This feature is coming for every type of definition, but will not include export procedures.
