### ISSUE TITLE
Error on stack call

### ISSUE THREAD

**Issue by basim1971** [halcyon-tech/vscode-rpgle#195]
All,
Do you know how i can bypass this error ? At the moment the oly solution is disable the addins.
Thanks for your great support
Project Mode enabled: false
[Error - 14:28:37] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Maximum call stack size exceeded
  Code: -32603

**Comment by worksofliam** [comment]
@basim1971 The only way for us to recreate this error is if you provide a sample piece of code so we can recreate it.

Thanks!

**Comment by basim1971** [comment]
Hi
In the meantime i try to understand which data can issue this problem.
So if you copy paste this code in a program you can replicate the problem.
Take into consideration that this code have an error. end-pr after dcl-pi it's not correct but this cause the problem
Hope this can help
Thanks 
//***********************************************************************
//*** Scompone la stringa per sql                                     ***
//***********************************************************************
Dcl-Proc ScomponiStringa;

  Dcl-Pi ScomponiStringa varchar(2000);
    pstringa varchar(999);
    pLunghezza zoned(3);
  End-Pr;
dcl-s lStringa varchar(2000);
dcl-s linizio zoned(4);
lInizio = 1;
Dow pStringa(lInizio:pLunghezza)<>*blank;
  lStringa +=sQuote+ pstringa(linizio:pLunghezza)+sQuote;
  linizio=linizio+pLunghezza
  If pstringa(linizio:1) <> *blank;
    lStringa +=pstringa(linizio:1);
  EndIf;
  linizio+=1;
EndDo;
Return lStringa;
End-Proc ScomponiStringa;

**Comment by worksofliam** [comment]
@basim1971 Can you also share your `rpglint.json` file if you have one?

**Comment by worksofliam** [comment]
I have recreated this issue.
