### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#2]
I'd like a logo for this extension. Is there an RPG mascot we could make use of or something?

**Comment by priceaj** [comment]
I think the logo should be an RPG launcher. You could subtitle the extension "RPG language tools: blowing up bad code!"

**Comment by worksofliam** [comment]
@priceaj lol! I love the enthusiasm.

For now, we have this, but absolutely subject to change. I want to create logos for all the extensions :)

![](https://raw.githubusercontent.com/halcyon-tech/vscode-rpgle/main/media/logo.png)
