### ISSUE TITLE
Support for code in local workspace

### ISSUE THREAD

**Issue by SpiderEkb** [halcyon-tech/vscode-rpgle#20]
What should I include in the settings for the outline view to work?
I work with a file not on a local computer. Extension - .rpgle 
File starts with ** free

**Comment by worksofliam** [comment]
Please share a code sample which isn't working. It should work by default.

**Comment by SpiderEkb** [comment]
This is an abbreviated version. The whole code is, firstly, very long, and secondly, I cannot show it.

===========================================================================
**FREE
  //  *C  DBGVIEW(*COPY)
       CTL-OPT  DECEDIT('.') DATEDIT(*DMY/)
                OPTION(*SRCSTMT:*SHOWCPY:*NODEBUGIO) 
                CVTOPT(*DATETIME)
                ACTGRP(*CALLER) DFTACTGRP(*NO) PGMINFO(*NO)
                DEBUG
                ALWNULL(*USRCTL)
                BNDDIR('EQBNDDIR' : 'LESBNDDIR' : 'ECLBNDDIR')
                DFTNAME(ECLCHK)
                MAIN(ECLCHK);


      dcl-ds t_qdsInputParams qualified template;
        Mode      char(1)       inz(*blank);  
                                              
                                              
                                              
        ChkType   char(1)       inz(*blank);  
                                              
                                              
                                              
        CliType   char(1)       inz(*blank);  
                                              
                                              
                                              
        Name      char(2048)    inz(*blanks); 
        DTBR      zoned(7 : 0)  inz(*zero);   
        CRF       char(20)      inz(*blanks); 
        DUL       char(60)      inz(*blanks); 
      end-ds;

      dcl-ds t_qdsKey qualified template;
        Lst       char(5)       inz(*blanks);
        SId       char(15)      inz(*blanks);
      end-ds;

      dcl-ds t_qdsSIDs qualified template;
        dsKey     likeds(t_qdsKey)   inz(*likeds);
        CliType   char(1)            inz(*blank);
      end-ds;

      dcl-ds t_qdsExitData qualified template;
        dsKey     likeds(t_qdsKey)   inz(*likeds);
        IIF       char(1)            inz(*blank);
        Typ       char(2)            inz(*blank);
      end-ds;


      dcl-ds dsSTLCHKRes qualified;
        ResW        char(1)     inz(*blank);
        ResS        char(1)     inz(*blank);
        ResB        char(1)     inz(*blank);
        pELMIDSet   pointer     inz(*null);
        pSIDList    pointer     inz(*null);  
      end-ds;

      dcl-ds dsNameLists qualified;
        pNameBRDTList      pointer    inz(*null);  
        pNameYRList        pointer    inz(*null);  
        pNameNoBRYRList    pointer    inz(*null);  
      end-ds;
      

      dcl-proc ECLCHK;
        dcl-pi *N;
          Mode      char(1);                      
          Tp          char(1);                    
          ChkTp       char(1);                    
          pChkData    pointer;                    
          Count       packed(2 : 0);              
          Res         char(1);                    
          IDArr       char(10)    dim(cMaxOutCnt);
          ResW        char(1);                    
          ResS        char(1);                    
          ResB        char(1);                    
          LSTArr      char(5)     dim(cMaxOutCnt);
          SIdArr      char(15)    dim(cMaxOutCnt);
          IIFArr      char(1)     dim(cMaxOutCnt);
          TYPArr      char(2)     dim(cMaxOutCnt);
          Error       char(37);                   
        end-pi ;

        dcl-s  RscnClTpOnly     ind                      inz(*off);
        dcl-s  SIDChngd         ind                      inz(*off);
        dcl-ds dsParams         likeds(t_qdsInputParams) inz(*likeds);
        dcl-ds dsLastParams     likeds(t_qdsInputParams) inz(*likeds)  static;

        clear Count ;
        clear Res   ;
        clear IDArr ;
        clear ResW  ;
        clear ResS  ;
        clear ResB  ;
        clear LSTArr;
        clear SIdArr;
        clear IIFArr;
        clear TYPArr;
        clear Error;
        clear dsSTLCHKRes.ResS;
        clear dsSTLCHKRes.ResW;
        clear dsSTLCHKRes.ResB;
      
        ParseInputParams(Mode : Tp : ChkTp : pChkData : dsParams : Error);

        GetELMIDs(dsParams.Mode : dsParams.CliType : dsParams.Name : RscnClTpOnly);
        GetNameDTBRs(dsParams.DTBR);
        GetDULs(dsParams.DUL);
        GetCRFs(dsParams.CliType : dsParams.CRF);
        MakeTotalList();

        FillOutParams(dsParams.ChkType : Count : Res : IDArr : ResW : ResS : ResB : LSTArr : SIdArr : IIFArr : TYPArr);

        exsr ExitSr;

        return;

        //---------------------------------------------------------------------
        begsr ExitSr;
          if Error <> *blanks;
            Snd_Inf_Msg(%subst(Error : 8 : 30): %subst(Error : 1 : 7) : *omit: *omit);
          else; 
            dsLastParams = dsParams;
          endif;

          return;
        endsr;

      end-proc;

      dcl-proc FillOutParams;
        dcl-pi *n;
          ChkType     char(1);
          Count       packed(2 : 0);              
          Res         char(1);                    
          IDArr       char(10)    dim(cMaxOutCnt);
          ResW        char(1);                    
          ResS        char(1);                    
          ResB        char(1);                    
          LSTArr      char(5)     dim(cMaxOutCnt);
          SIdArr      char(15)    dim(cMaxOutCnt);
          IIFArr      char(1)     dim(cMaxOutCnt);
          TYPArr      char(2)     dim(cMaxOutCnt); 
        end-pi;     

      end-proc;


      dcl-proc MakeTotalList;
        dcl-pi *n;
        end-pi;

      end-proc;


      //=======================================================================
      // Проверка совпадений ИНН
      //=======================================================================
      dcl-proc GetCRFs;
        dcl-pi *n;
          CliType      char(1);
          CRF          char(20);
        end-pi;

      end-proc;


      dcl-proc GetDULs;
        dcl-pi *n;
          DUL          char(60);
        end-pi;

      end-proc;

      dcl-proc GetNameDTBRs;
        dcl-pi *n;
          DTBR          zoned(7 : 0);
        end-pi;

      end-proc;


      dcl-proc GetELMIDs;
        dcl-pi *n;
          Mode          char(1);
          CliType       char(1);
          Name          char(2048);
          RscnClTpOnly  ind;
        end-pi;

      end-proc;


      //=======================================================================
      // Анализ входных параметров
      //=======================================================================
      dcl-proc ParseInputParams;
        dcl-pi *n;
          Mode        char(1)     value;
          Tp          char(1)     value;
          ChkTp       char(1)     value;
          pChkData    pointer     value;
          dsParams    likeds(t_qdsInputParams);
          dsError     likeds(DS_ErrorMessageData);
        end-pi;
 
      end-proc;
===========================================================================

**Comment by worksofliam** [comment]
Looks like it works for me.

![image](https://user-images.githubusercontent.com/3708366/144458821-44a317b6-9b62-45ba-9ea1-ea069d1da454.png)

What version of the extension do you have installed?

**Comment by SpiderEkb** [comment]
I am using the latest version installed from VSCode Marketplace - RPG Language Tools 0.0.6
The problem may be that I am working with files on the local computer, not on the IBM i server. And VSCode is not connected to the server
![VSCODE](https://user-images.githubusercontent.com/29450542/144468888-abdc8e0b-71d7-43f5-9580-aaf8a8733ced.PNG)

**Comment by worksofliam** [comment]
@SpiderEkb Ah, that'd be why. For the time being, we're really focusing on files on the remote server (since that's where the majority of our users are writing code).

With that being said, I do think that support for code on the local machine would be simple enough to implement in the future.

**Comment by SpiderEkb** [comment]
Well, we have a slightly different scheme of work ...
We work with Git, gradle and jenkins. From the local computer, we commit to git, and from there, jenkins using gradle builds the patch and places it on the IBM i server and in the artifactory. We almost never work with source files on the server.

**Comment by worksofliam** [comment]
@SpiderEkb I am completely envious of that setup. Sounds great. 

We actually had a PR a few months back that added support for local development (which included the content assist, etc), where it would let the user write all the code on the local machine, and upload only what's depended on and used to be compiled. Was really neat, but lack of interest had it removed.

I will make sure this gets done for you. There are a couple of other pressing issues which need to get sorted first.

**Comment by SpiderEkb** [comment]
Barry, good news. Very happy with the perspective of a working outline in vscode
Our scheme of work is due to the fact that we have a lot of units on the server. The patch is first put in a component testing unit, then in a business testing unit, then load and integration testing, then a prelive unit, and only then in production
Besides, there are many teams, many developers, many projects. It is more convenient to store all this in git and not on the server.

**Comment by worksofliam** [comment]
@SpiderEkb I got this working today as I needed it for my new unit tests. Should be out this week.

**Comment by worksofliam** [comment]
Will only work for IFS styled copy/include statements

![image](https://user-images.githubusercontent.com/3708366/144762913-196aa787-3c7d-4ff2-8b6f-e8aa2adc3a76.png)

**Comment by worksofliam** [comment]
@SpiderEkb In 0.0.8, support for local file system outline has been added.

**Comment by SpiderEkb** [comment]
@worksofliam Unfortunately, after updating the plugin version to 0.0.8, nothing has changed :-(
As before "No symbols found in document"

Sample code:

`**FREE
  //  *C  DBGVIEW(*COPY)
  //  *-------------------------------------------------------------------------
  //  *              System Name - EQUATION
  //  *              Module Name - MQTSND
  //  *
  //  *             Program Name - MQTSND
  //  *            Program Title - Тест посылки сообщения в MQ с допинфо в заголовке
  //  *
  //  *  Входные параметры:
  //  *
  //  *L                   Level - 100
  //  *
  //  *            Creation Date - 08.07.2021
  //  *      Last Amendment Date -   .  .
  //  *H------------------------------------------------------------------
  //  *H Change Control
  //  *H ~~~~~~~~~~~~~~
  //  *H Project     Programmer       Date       Level
  //  *H ~~~~~~~     ~~~~~~~~~~     ~~~~~~~~     ~~~~~
  //  *H             Поморцев В.    08.07.21      100
  //  *-------------------------------------------------------------------------
      CTL-OPT  DECEDIT('.') DATEDIT(*DMY/)
              OPTION(*SRCSTMT:*SHOWCPY:*NODEBUGIO) 
              CVTOPT(*DATETIME)
              ACTGRP(*CALLER) DFTACTGRP(*NO) PGMINFO(*NO)
              DEBUG
              ALWNULL(*USRCTL)
              BNDDIR('EQBNDDIR' : 'LESBNDDIR' : 'MQBNDDIR')
              DFTNAME(MQTSND)                             //<=== Имя программы
              MAIN(MQTSND)
              TEXT('Тест посылки сообщения в MQ с допинфо в заголовке'); //<=== Наименование


      /INCLUDE EQCPYLESRC,STDCNST  // Standard program constanrd prog
      /INCLUDE SKLCPYSRC,DSSYSE_F  // Data Structure of DASYSCTL data area
      /INCLUDE SKLCPYSRC,DSJOBE_F  // Data structure for data area DAJOBCTLE

      /INCLUDE ABCPYLESRC,DEF_PSDS     // Определение структуры данных статуса программы (PSDS)
      /INCLUDE ABCPYLESRC,DECLARE_DS
      /INCLUDE ABCPYLESRC,DECLARE_PR

      /INCLUDE ABCPYLESRC,TASSRVRPGP
      /INCLUDE ABCPYLESRC,LESSRVRPGP
      /INCLUDE ABCPYLESRC,MQSSRVRPGP
      /INCLUDE EQCPYLESRC,DSEPMS

      // MQI named constants
      /INCLUDE CMQG

      Dcl-F QsysPrt Printer(132) UsrOpn;

      Dcl-Ds dbgOutputStr; 
        *N Char(132); 
      End-Ds;


      // --------------------------------------------------
      // Prototype for main procedure
      // --------------------------------------------------
      dcl-proc MQTSND;
        dcl-pi *n;
        // список аргументов главной процедуры
        end-pi ;

        Dcl-S IsInitialized     Ind Inz(#false) Static;
        Dcl-S DontCreateDumpPtr Pointer         Static;
        Dcl-S DontCreateDump    Ind Based(DontCreateDumpPtr);
        Dcl-S CancelHandlerPtr  Pointer(*proc) Inz(%paddr(PgmCancel));

        dcl-s  MQMgrName        char(48)   inz('MQMALFAMOS2');
        dcl-s  MQQueName        char(48)   inz('A.TEST.Q');
        dcl-s  MQMsgId          char(10)   inz('MQRFH2TEST');
        dcl-s  msgOutLen        int(10);

        dcl-c  PropNameMax      const(256);
        dcl-c  PropValueMax     const(256);

        dcl-s  PropertyName     char(PropNameMax);
        dcl-s  PropertyValue    char(PropValueMax);    

        dcl-s  i                int(3);

        dcl-ds CONN qualified static;
          hConn   int(10) Inz(*zero);
          hObj    int(10) Inz(*zero);
          hMsg    int(20) inz(*zero);
          OCode   int(10) Inz(*zero);
          Reason  int(10) Inz(*zero);
        end-ds;

        dcl-ds dsMsgOut    qualified         static;
          outHdr           char(10)          inz(*blanks);          
          outBuffer        char(32767)       inz(*blanks);
        end-ds;

        If Not IsInitialized;
          CeeRtx( CancelHandlerPtr : %addr(ProgramStatusInfo) : *omit );
          ModuleInit( DontCreateDumpPtr );
          IsInitialized = #true;
        EndIf;

        if not %open(QsysPrt);
          open QsysPrt;
        endif;

        if MQConnect(MQMgrName : MQQueName : CONN.hConn : CONN.hObj : 
                     CONN.OCode : CONN.Reason);
          CONN.hMsg = CreateMsgHandle(CONN.hConn : CONN.OCode : CONN.Reason);

          if CONN.hMsg <> -1;
            // for i = 1 to 1;
            //   PropertyName  = 'ctx.Property' + %editc(i : 'X');
            //   PropertyValue = 'Property #' + %editc(i : 'X') + ' data';

            //   if not SetMsgProp(CONN.hConn : CONN.hMsg : TYPSTR :
            //                     PropertyName : %len(%trimr(PropertyName)) :
            //                     PropertyValue : %len(%trimr(PropertyValue)) :
            //                     CONN.OCode : CONN.Reason);
            //     leave;
            //   endif;
            // endfor;

            PropertyName  = 'ctx_Property001';
            PropertyValue = 'Property #001' + ' data';

            SetMsgProp(CONN.hConn : CONN.hMsg : TYPSTR :
                        PropertyName : %len(%trimr(PropertyName)) :
                        PropertyValue : %len(%trimr(PropertyValue)) :
                        CONN.OCode : CONN.Reason);

            // PropertyName  = 'usr.Property002';
            // PropertyValue = 'Property #002' + ' data';

            // SetMsgProp(CONN.hConn : CONN.hMsg : TYPSTR :
            //             PropertyName : %len(%trimr(PropertyName)) :
            //             PropertyValue : %len(%trimr(PropertyValue)) :
            //             CONN.OCode : CONN.Reason);

            dsMsgOut.outHdr    = MQMsgId;
            dsMsgOut.outBuffer = 'Test message body';
            msgOutLen          = %size(dsMsgOut.outHdr) + 
                                 %len(%trimr(dsMsgOut.outBuffer));

            PutMessage(MQMgrName : MQQueName : CONN.hConn : CONN.hObj : CONN.hMsg :
                       dsMsgOut : msgOutLen : CONN.OCode : CONN.Reason);
            DeleteMsgHandle(CONN.hConn : CONN.hMsg : CONN.OCode : CONN.Reason);
          endif;

          MQDisconnect(CONN.hConn : CONN.hObj : CONN.OCode : CONN.Reason);
        endif;

        if %open(QsysPrt);
          close QsysPrt;
        endif;

        return;

        BegSr *pssr;
          CommonErrorHandler( DontCreateDump );
        EndSr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: PutMessage
      // --------------------------------------------------
      dcl-proc PutMessage;
        dcl-pi *n ind;
          MQMgr     char(48);
          MQQueue   char(48);
          hConn     int(10);
          hObj      int(10);
          hMsg      int(20);
          Buffer    char(32767)    options(*varsize);
          BuffLen   int(10)        value;
          OC        int(10);
          RC        int(10);
        end-pi;

        // Message Descriptor
        dcl-ds dsMQMD qualified;
          /INCLUDE CMQMDG
        end-ds;

        // Pet message options
        dcl-ds dsMQPMO qualified;
          /INCLUDE CMQPMOG
        end-ds;

        dcl-s  indRes      ind          inz(*off);

        dsMQPMO.PMOPT = %bitor(PMFIQ : PMNSYP : PMNCID);
        dsMQPMO.PMVER = PMVERC;
        dsMQPMO.PMOMH = hMsg;   

        dsMQMD.MDFMT = FMNONE;

        MQPUT(hConn : hObj : dsMQMD : dsMQPMO : BuffLen : %addr(Buffer) : OC : RC);

        if RC <> RCNONE;
          MQDisconnect(hConn : hObj : OC : RC);

          if MQConnect(MQMgr : MQQueue : hConn : hObj : OC : RC);
            MQPUT(hConn : hObj : dsMQMD : dsMQPMO : BuffLen : %addr(Buffer) : OC : RC);
          endif;
        endif;

        if RC = RCNONE;
          dbgOutputStr = 'Message Sent';
          Write QsysPrt dbgOutputStr;

          dbgOutputStr = 'Message: ' + Buffer; 
          Write QsysPrt dbgOutputStr;

          indRes = *on;
        else;
          dbgOutputStr = 'MQPUT RC: ' + %char(RC);
          Write QsysPrt dbgOutputStr;
        endif;

        return indRes;

        begsr *pssr;
          dump;
        endsr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: SetMsgProp
      // --------------------------------------------------
      dcl-proc SetMsgProp;
        dcl-pi *n ind;
          hConn       int(10);
          hMsg        int(20);
          PropType    int(10)        value;
          PropName    char(32767)    options(*varsize);
          PropNameLen int(10)        value;
          PropVal     char(32767)    options(*varsize);
          PropValLen  int(10)        value;
          OC          int(10);
          RC          int(10);
        end-pi;

        dcl-ds dsPropName Qualified static; 
          /INCLUDE CMQCHRVG
        end-ds;

        dcl-ds dsMQSMPO qualified static;
          /INCLUDE CMQSMPOG
        end-ds;

        dcl-ds dsMQPD qualified static;
          /INCLUDE CMQPDG
        end-ds;

        dcl-s  indRes     ind      inz(*off);

        dsPropName.VCHRP = %addr(PropName);
        dsPropName.VCHRL = PropNameLen;

        dsMQPD.PDSUP = PDSUPO;
        dsMQPD.PDVER = PDVERC;
        dsMQPD.PDCT  = PDUSC;

        MQSETMP(hConn : hMsg : dsMQSMPO : dsPropName : dsMQPD : PropType : 
                PropValLen : %addr(PropVal) : 
                OC : RC);

        if RC = RCNONE;
          dbgOutputStr = 'Message Property set';
          Write QsysPrt dbgOutputStr;

          dbgOutputStr = 'Property Name : ' + PropName; 
          Write QsysPrt dbgOutputStr;

          dbgOutputStr = 'Property Value: ' + %char(PropVal); 
          Write QsysPrt dbgOutputStr;

          indRes = *on;
        else;
          dbgOutputStr = 'MQSETMP RC: ' + %char(RC);
          Write QsysPrt dbgOutputStr;
        endif;

        return indRes;

        begsr *pssr;
          dump;
        endsr;
      end-proc;


      // --------------------------------------------------
      // Procedure name: MQDisconnect
      // --------------------------------------------------
      dcl-proc MQDisconnect;
        dcl-pi *n;
          hConn     int(10);
          hObj      int(10);
          OC        int(10);
          RC        int(10);
        end-pi;

        if hObj <> *Zero;
          MQCLOSE(hConn : hObj : CONONE : OC : RC);
          clear hObj;
        endif;

        if hConn <> *Zero;
          MQDISC(hConn : OC : RC);
          clear hConn;
        endif;

        return;

        begsr *pssr;
          dump;
        endsr;
      end-proc;


      // --------------------------------------------------
      // Procedure name: MQConnect
      // --------------------------------------------------
      dcl-proc MQConnect;
        dcl-pi *n ind;
          MQMgr     char(48);
          MQQueue   char(48);
          hConn     int(10);
          hObj      int(10);
          OC        int(10);
          RC        int(10);
        end-pi;

        // Object Descriptor
        dcl-ds dsMQOD qualified;
          /INCLUDE CMQODG
        end-ds;

        dcl-s  indRes    ind   inz(*off);
        dcl-s  opts      int(10);

        // Установка соединения с MQ
        MQCONN(MQMgr : hConn : OC : RC);

        if OC = CCOK;
          // Открытие очереди на чтение
          opts = %bitor(OOOUT : OOFIQ);
          dsMQOD.ODON = MQQueue;

          MQOPEN(hConn : dsMQOD : opts : hObj : OC : RC);

          if RC = RCNONE;
            indRes = *on;
          else;
            dbgOutputStr = 'MQOPEN RC: ' + %char(RC);
            Write QsysPrt dbgOutputStr;
          endif;
        else;
          dbgOutputStr = 'MQCONN RC: ' + %char(RC);
          Write QsysPrt dbgOutputStr;
        endif;

        return indRes;

        begsr *pssr;
          dump;
        endsr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: CreateMsgHandle
      // --------------------------------------------------
      dcl-proc CreateMsgHandle;
        dcl-pi *n int(20);
          hConn     int(10);
          OC        int(10);
          RC        int(10);
        end-pi;

        dcl-ds dsMQCMHO qualified;
          /INCLUDE CMQCMHOG
        end-ds;

        dcl-s  hMsg     int(20)   inz(-1);

        dsMQCMHO.CMVER = CMVERC;

        MQCRTMH(hConn : dsMQCMHO : hMsg : OC : RC);

        if RC <> RCNONE;
          dbgOutputStr = 'MQCRTMH RC: ' + %char(RC);
          Write QsysPrt dbgOutputStr;

          hMsg = -1;
        endif;

        return hMsg;

        begsr *pssr;
          dump;
        endsr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: DeleteMsgHandle
      // --------------------------------------------------
      dcl-proc DeleteMsgHandle;
        dcl-pi *n ;
          hConn     int(10);
          hMsg      int(20);
          OC        int(10);
          RC        int(10);
        end-pi;

        dcl-ds dsMQDMHO qualified;
          /INCLUDE CMQDMHOG
        end-ds;

        dsMQDMHO.DMVER = DMVERC;

        MQDLTMH(hConn : hMsg : dsMQDMHO : OC : RC);

        if RC <> RCNONE;
          dbgOutputStr = 'MQDLTMH RC: ' + %char(RC);
          Write QsysPrt dbgOutputStr;
        endif;

        return;

        begsr *pssr;
          dump;
        endsr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: ModuleInit
      // Purpose:
      // Returns:
      // Parameter:      DontCreateDumpPtr
      // --------------------------------------------------
      Dcl-Proc ModuleInit;
        Dcl-Pi *N;
          DontCreateDumpPtr Pointer;
        End-Pi;

        Dcl-S DontCreateDump       Ind     Based(DontCreateDumpPtr);
        Dcl-S FuncStatus           Char(6) Based(FuncStatusPtr);
        Dcl-S CommitControlStatus  Ind     Based(CommitControlStatusPtr);

        Dcl-S ProgramStatusInfoPtr Pointer Inz(%addr(ProgramStatusInfo));

        // Do initialization processing
        If PgmINZSR( ProgramStatusInfoPtr : FuncStatusPtr :
                    CommitControlStatusPtr : DontCreateDumpPtr );
            CommonErrorHandler( DontCreateDump );
        EndIf;

        In DSSYSE;          // read system control data area DASYSCTL
        In DSJOBE;          // read job control data area DAJOBCTLE

        return ;
      END-PROC ;

      // --------------------------------------------------
      // Procedure name: CommonErrorHandler
      // Purpose:
      // Returns:
      // Parameter:      DontCreateDump
      // --------------------------------------------------
      Dcl-Proc CommonErrorHandler;
        Dcl-Pi *N Char(6);
            DontCreateDump Ind Const;
        End-Pi;

        Dcl-S PssrReturn   Char(6);
        Dcl-S PssrAttempts Packed(1:0) Inz(0) Static;
        Dcl-S PssrMsgId    Char(7);

        PssrReturn = '*CANCL';
        PssrAttempts += 1;

        If PssrAttempts = 1;
          // Вызываем стандартный обработчик исключиней
          CallP PgmPSSR( %addr(ProgramStatusInfo) : PssrReturn :
                        *on : *on : *on : ProgramStatusInfo.@PGMID :
                        PssrMsgId );

          If (%addr(DontCreateDump) = *null) Or (Not DontCreateDump);
            Dump(A) ProgramStatusInfo.@PGMID;
          EndIf;
        EndIf;

        // If Commitment Control is active, roll back transaction.
        If (PssrAttempts = 0) Or (PssrAttempts = 1) Or (PssrAttempts = 2);
          PgmAbortTran( %addr(ProgramStatusInfo) : *on );
        EndIf;

        Return PssrReturn;
      End-Proc;
`
This is the complete code, no abbreviations.

**Comment by worksofliam** [comment]
@SpiderEkb Not sure how you've managed that, but I am seeing content in the outline view myself. Is the language type RPGLE?

![image](https://user-images.githubusercontent.com/3708366/144860549-ae6dd0e3-e982-48fe-b5ae-03402d25e3fc.png)

Another thing I am seeing is that you're using the member-styled paths on your `/INCLUDE` statements. It won't like that.. got to think about how to support those from the local source.

**Comment by SpiderEkb** [comment]
@worksofliam bingo! The problem was in language mode. For some reason, I had RPG language mode set for these files. Forcing RPGLE language mode for .rpgle and .sqlrpgle files helped - now everything works correctly.
Thank you so much for your work and for the tip.

**Comment by worksofliam** [comment]
@SpiderEkb Excellent!! Next step is better support for your include statements using the member style path.

**Comment by SpiderEkb** [comment]
@worksofliam With this, everything is complicated. I do not have a permanent connection to the IBM i server (for some reason the plugin cannot establish it, possibly because SSH is closed on our server, ACS is working, but the plugin is not connected). Therefore, there is no access to Copysource members from VSCode
![ALFAMOSVPN](https://user-images.githubusercontent.com/29450542/144864885-9f507389-2ca7-4584-8e3c-ebb3f2dd08f6.PNG)

**Comment by worksofliam** [comment]
@SpiderEkb Got that part.. do you have those sources on your local machine in the workspace?

**Comment by SpiderEkb** [comment]
@worksofliam unfortunately, I was forced to disable the plugin due to the fact that it causes a very large lag when pressing any key when typing code in RPGLE files :-(

**Comment by worksofliam** [comment]
@SpiderEkb how big was your file? I can work on that

**Comment by worksofliam** [comment]
@SpiderEkb I just released 0.0.9, which adds some minor performance improvements. The linter no longer runs on every change, and will only lint/parse after you've stopped typing for a couple of seconds.

Also, if you could provide me with the length of your file, that'd be great for my testing.

**Comment by SpiderEkb** [comment]
@worksofliam the file is very small:

`**FREE
  //  *C  DBGVIEW(*COPY)
  //  *-------------------------------------------------------------------------
  //  *              System Name - EQUATION
  //  *              Module Name -
  //  *
  //  *             Program Name -
  //  *            Program Title -
  //  *
  //  *  Входные параметры:
  //  *
  //  *L                   Level -
  //  *
  //  *            Creation Date -   .  .
  //  *      Last Amendment Date -   .  .
  //  *H------------------------------------------------------------------
  //  *H Change Control
  //  *H ~~~~~~~~~~~~~~
  //  *H Project     Programmer       Date       Level
  //  *H ~~~~~~~     ~~~~~~~~~~     ~~~~~~~~     ~~~~~
  //  *H             Поморцев В.      .  .
  //  *-------------------------------------------------------------------------
      CTL-OPT  DECEDIT('.') DATEDIT(*DMY/)
              OPTION(*SRCSTMT:*SHOWCPY:*NODEBUGIO) 
              CVTOPT(*DATETIME)
              ACTGRP(*CALLER) DFTACTGRP(*NO) PGMINFO(*NO)
              DEBUG
              ALWNULL(*USRCTL)
              BNDDIR('EQBNDDIR')
              DFTNAME(SPOOLTST)                             //<=== Имя программы
              MAIN(SPOOLTST)
              TEXT('SPOOLTST'); //<=== Наименование


      /INCLUDE EQCPYLESRC,STDCNST  // Standard program constanrd prog
      /INCLUDE SKLCPYSRC,DSSYSE_F  // Data Structure of DASYSCTL data area
      /INCLUDE SKLCPYSRC,DSJOBE_F  // Data structure for data area DAJOBCTLE

      /INCLUDE ABCPYLESRC,DEF_PSDS     // Определение структуры данных статуса программы (PSDS)
      /INCLUDE ABCPYLESRC,DECLARE_DS
      /INCLUDE ABCPYLESRC,DECLARE_PR

      /INCLUDE ABCPYLESRC,TASSRVRPGP
      /INCLUDE ABCPYLESRC,LESSRVRPGP
      /INCLUDE EQCPYLESRC,DSEPMS

      Dcl-F QsysPrt Printer(132) UsrOpn;

      Dcl-Ds dbgOutputStr; 
        *N Char(132); 
      End-Ds;

      // --------------------------------------------------
      // Prototype for main procedure
      // --------------------------------------------------
      dcl-proc SPOOLTST;
        dcl-pi *n;
        // список аргументов главной процедуры
        end-pi ;

        Dcl-S IsInitialized     Ind Inz(#false) Static;
        Dcl-S DontCreateDumpPtr Pointer         Static;
        Dcl-S DontCreateDump    Ind Based(DontCreateDumpPtr);
        Dcl-S CancelHandlerPtr  Pointer(*proc) Inz(%paddr(PgmCancel));

        dcl-s  i                  int(5);
        dcl-s  j                  int(5);

        If Not IsInitialized;
          CeeRtx( CancelHandlerPtr : %addr(ProgramStatusInfo) : *omit );
          ModuleInit( DontCreateDumpPtr );
          IsInitialized = #true;
        EndIf;

        // тут смысловая часть - что оно должно делать
        for i = 1 to 3;
          open QsysPrt;

            dbgOutputStr = 'Spool #' + %char(i);
            Write QsysPrt dbgOutputStr;

            for j = 1 to 10;
              dbgOutputStr = '  - Line #' + %char(j);
              Write QsysPrt dbgOutputStr;
            endfor;

          close QsysPrt;
        endfor;

        BegSr *pssr;
          CommonErrorHandler( DontCreateDump );
        EndSr;
      end-proc;

      // --------------------------------------------------
      // Procedure name: ModuleInit
      // Purpose:
      // Returns:
      // Parameter:      DontCreateDumpPtr
      // --------------------------------------------------
      Dcl-Proc ModuleInit;
        Dcl-Pi *N;
          DontCreateDumpPtr Pointer;
        End-Pi;

        Dcl-S DontCreateDump       Ind     Based(DontCreateDumpPtr);
        Dcl-S FuncStatus           Char(6) Based(FuncStatusPtr);
        Dcl-S CommitControlStatus  Ind     Based(CommitControlStatusPtr);

        Dcl-S ProgramStatusInfoPtr Pointer Inz(%addr(ProgramStatusInfo));

        // Do initialization processing
        If PgmINZSR( ProgramStatusInfoPtr : FuncStatusPtr :
                    CommitControlStatusPtr : DontCreateDumpPtr );
            CommonErrorHandler( DontCreateDump );
        EndIf;

        In DSSYSE;          // read system control data area DASYSCTL
        In DSJOBE;          // read job control data area DAJOBCTLE

        return ;
      end-proc ;

      // --------------------------------------------------
      // Procedure name: CommonErrorHandler
      // Purpose:
      // Returns:
      // Parameter:      DontCreateDump
      // --------------------------------------------------
      Dcl-Proc CommonErrorHandler;
        Dcl-Pi *N Char(6);
            DontCreateDump Ind Const;
        End-Pi;

        Dcl-S PssrReturn   Char(6);
        Dcl-S PssrAttempts Packed(1:0) Inz(0) Static;
        Dcl-S PssrMsgId    Char(7);

        PssrReturn = '*CANCL';
        PssrAttempts += 1;

        If PssrAttempts = 1;
          // Вызываем стандартный обработчик исключиней
          CallP PgmPSSR( %addr(ProgramStatusInfo) : PssrReturn :
                        *on : *on : *on : ProgramStatusInfo.@PGMID :
                        PssrMsgId );

          If (%addr(DontCreateDump) = *null) Or (Not DontCreateDump);
            Dump(A) ProgramStatusInfo.@PGMID;
          EndIf;
        EndIf;

        // If Commitment Control is active, roll back transaction.
        If (PssrAttempts = 0) Or (PssrAttempts = 1) Or (PssrAttempts = 2);
          PgmAbortTran( %addr(ProgramStatusInfo) : *on );
        EndIf;

        Return PssrReturn;
      End-Proc;
`
in the new version it has become noticeably better. Although sometimes there is a slight lag. I can’t say for sure if it’s annoying yet.

**Comment by worksofliam** [comment]
@SpiderEkb lovely. Thanks for sharing. Let me have a play with that and see what improvements I can make!

**Comment by SpiderEkb** [comment]
@worksofliam still there is a lag. And he's annoying. The lag is not constant as in the previous version. It appears periodically.

**Comment by SpiderEkb** [comment]
@worksofliam Still, the lag remains and quite unpleasant. Hinders work.
If it matters. Windows 10/64
AMD Athlon 300U 2.4 GHz 2 Cores 4 Threads
16Gb RAM 512Gb SDD

**Comment by worksofliam** [comment]
@SpiderEkb Good evening. I have released 0.0.10 which may solve this issue. I was able to recreate it.

**Comment by SpiderEkb** [comment]
@worksofliam thanks, at first glance everything looks much better.

**Comment by SpiderEkb** [comment]
@worksofliam I can say with almost complete confidence that everything is working well now. Lags are not noticeable.
