### ISSUE TITLE
Feature Request: Additional hover tip info for variables

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/vscode-rpgle#200]
Would it be possible to add which file a file is defined in in the hover tip, having to ctrl + click to find out is a bit annoying

**Comment by worksofliam** [comment]
Nice idea. I will look into it!

**Comment by worksofliam** [comment]
Looks like we only do it for procedures at the moment. Should be simple to add to others.

https://github.com/halcyon-tech/vscode-rpgle/blob/main/server/src/providers/hover.ts#L53

**Comment by priceaj** [comment]
the File and type definition definitely appear (using fixed format code)

**Comment by priceaj** [comment]
Oh I see, thought you meant it was ONLY done for prototypes and procedures

**Comment by worksofliam** [comment]
I have made a change to show the `@file` property on all hover situations when the definition is an external file. This applies to all variables and procedures.

When defined in the same source:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/3708366/218272563-9af43b9e-6635-4e61-942d-91b747abc97b.png">

When defined externally:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3708366/218272521-329823c7-07d3-4b3d-9760-f25e025c89bc.png">
