### ISSUE TITLE
rpgleIndentation: Add "Quick Fix"

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#21]
Can we add Quick Fix capability when an indentation error is reported?  Also with the option to fix all indentation errors in the member.

**Comment by worksofliam** [comment]
No quick fix as such, but now you can use the 'Fix all auto-fixable problems' command and it will fix them all!

What do you think of that @SJ?

**Comment by SJLennon** [comment]
It certainly cleaned up a lot of stuff when I used it on an old program!  Though I haven't extensively tested it.

My one gripe is that Ctrl+Z seems to remove changes one line at a time.  I think it would be nice if Ctrl+Z could reverse all the changes.  
@worksofliam
