### ISSUE TITLE
outline and lint not working

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/vscode-rpgle#22]
Hello, i am on MAC.
I have the extension vscode rpgle. I have enabled content assist, lint in the setting,
I have an RPGLE program (**Free), the lint and outline view is not working.
even the snippets %scan is not working

**Comment by worksofliam** [comment]
1. Please share a code sample.
2. What version of Code for IBM i and vscode-rpgle
3. Are you looking at source on the remote server too?

**Comment by AjaykulkarniIBMi** [comment]
![CleanShot 2021-12-06 at 08 42 10](https://user-images.githubusercontent.com/37787504/144865992-27f01da8-15f6-4b47-91d9-1949a9525cd1.png)
![CleanShot 2021-12-06 at 08 44 26](https://user-images.githubusercontent.com/37787504/144866287-afb74a96-6750-4220-bd49-05fb2ce3fb00.png)
![CleanShot 2021-12-06 at 08 45 00](https://user-images.githubusercontent.com/37787504/144866345-5d056151-1473-438b-92bb-4d4cad65228a.png)

**Comment by worksofliam** [comment]
@AjaykulkarniIBMi What is the language type of your source? RPG or RPGLE? 

Language type is not the same as extension.

**Comment by AjaykulkarniIBMi** [comment]
oh man, you are right...
sorry for not checking that...

are you planning on making a video or article on lint/outline etc?
