### ISSUE TITLE
prettyComments reports issue with ILEDOC comments

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#231]
I recently turned on prettyComments in the ILE Linter now I get linter warnings.
I am following the instructions at this [link ](https://halcyon-tech.github.io/docs/#/pages/developing/iledocs), to format function headers.

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/a805a74c-7d86-4e01-994a-74da69bebca4)

Letting the system fix the issue
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/f29d1788-5ded-43dd-ac2c-404c574b1bfc)
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/7dd62618-b6d3-4655-8e62-142700cad0fe)
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/839ad0aa-c39c-4d81-a323-d5a3f2342ff4)

I would prefer to have all function headers start with an indent so that when I fold all I only see the begin and end of each sub-routine or a function.
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/b575617e-8272-4cc9-be04-cab4cf291c48) 
But the prettyComments insists that I start my comments in position 1.  This should be configurable or not checked.

**Comment by worksofliam** [comment]
Please share a code snippet that I can recreate with.

**Comment by m-tyler** [comment]
test file
[ISSUE_231_RPGLE.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12131440/ISSUE_231_RPGLE.RPGLE.txt)

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/f154df17-1c59-4ad8-a4ce-b9343c2b72ad)

**Comment by worksofliam** [comment]
I have recreated it. Fix coming in some days

**Comment by m-tyler** [comment]
Sounds great.

**Comment by worksofliam** [comment]
This is out as of 0.20.0
