### ISSUE TITLE
Semi colon on separate line casues indent linter warnings

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#237]
Updating to 0.20.0 I now receive linter warnings for code like this.
Is there a new linter rule added for this in 0.20.0 that I need to set? 
This just an example of code that is longer that has this issue.  I like to move the semi colon to its own line for some conditions where I might be adding additional later, it reduces my need to remove and add semi colons when adding additional conditions.
```
**FREE
If MyVar <> ThatValue  //<<-- move semi colon here and the warning go away.  There are no warnings for this code in v0.19.0
;
  DoThisCode();
Else;
  CoThatCOde();
Endif;
*INLR = *ON;
Return;
```
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/9daa96a9-abda-43c7-bd49-88cedfccbf11)

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/6e2fdf37-38b1-4f22-862d-1866fde0df3e)

Example of in production code the new linter rules highlight.
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/acccb94b-5a66-46f8-873d-548a0850cf37)

**Comment by worksofliam** [comment]
There was big change to the internals of the linter and I suspect this is clearly from that. I will look into this.

**Comment by m-tyler** [comment]
This code also causes linter warnings to appear but for something that does not seem correct.  The semi colon on the SQL statement on a line by itself causes mp reference errors for the proc parameters.

```
**FREE
Dcl-S MyParm1 Char(1) Const;
Dcl-S MyParm2 Char(1) Const;
  exec sql 
        select 1 
        from MyTable
        Where MyField1 =:MyParm1 
        and MyField2 = :MyParm2
        ;
MyProc1();
*INLR = *ON;
Return;
dcl-proc MyProc1;
  dcl-pi *n ;
    pMyParm1 Char(1) Const;
    pMyParm2 Char(1) Const;
  end-pi;
  exec sql 
        select 1 
        from MyTable
        Where MyField1 =:pMyParm1 
        and MyField2 = :pMyParm2
        ; 
end-proc;
```

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/b5176fe8-ce5a-460b-bdd5-fbb3ab2e8d8f)

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/d1e522d9-4fa7-4238-bf26-e89cc268ce98)

**Comment by worksofliam** [comment]
Whoops, you must have comments right as I made a release. Can you please share your `rpglint.json` config so I can recreate that?

**Comment by worksofliam** [comment]
Try out the 0.20.1 release and let me know how it goes. Thanks!

**Comment by m-tyler** [comment]
Updated to 0.20.1 and now that linter warning is not present. 😀😀 VERY NICE!!!.


![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/b058eca1-ae99-483d-9d2c-bbf52a358a3b)


Thanks!!!

P.S. Do you want another issue I have come across with the update to 0.20.1 in this issue or anew issue?

**Comment by worksofliam** [comment]
@m-tyler new issue please!! Thanks for everything!
