### ISSUE TITLE
External API Error Message Flags the Wrong Line of Source

### ISSUE THREAD

**Issue by BrianGodsend** [halcyon-tech/vscode-rpgle#240]
I have the following setting configured in the RPGLINIT.JSON:

`"NoExternalTo": ["QCMD", "QP2TERM", "QSH", "SYSTEM", "QCMDEXC"]`

In my source, I have a rather long pre-amble (documentation), several definitions, and then eventually a prototype to `QCMDEXC`.  The error `Cannot declare prototype to this external API.` flags one of the comment lines in the pre-ample of the code.  It took me sometime to figure this one out.

The linter does correctly identify that I created a prototype to one of the restricted external programs; however, it is showing the error as being on a comment line, line 17.  The actual error is on the prototype definition way down on line 466.

In a greatly reduced example, the error is still being reported on the wrong line.  As indicated in the example below, the `Cannot declare prototype to this external API.` is being reported on the comment line with the error indicator flagging the four tildes as the cause of the error.

Note: Each *line* of source (comment or otherwise) added before the external prototype definition cause the error indicator to be moved one more character further into the source.  That is, if I added 3 additional lines after "Comment line 2" line, the error indicator would be moved over 3 characters to start on the last tilde, marking the text `~ <-` as being the cause of the error.  So, there seems to be some linkage to the number of lines, not the actual text on a given line (the lines could have any amount of text, the error indicator will only shift one character per line).

```RPGLE
**FREE

///
// -> ~~~~ <- This is where the error is reported
// Comment line 2
// Comment line 3
// Comment line 4
// Comment line 5
// Comment line 6
// Comment line 7
// Comment line 8
// Comment line 9
// Comment line 10
// Comment line 11
// Comment line 12
// Comment line 13
// Comment line 14
// Comment line 15
// Comment line 16
///

dcl-pr QCMDEXC  extpgm('QCMDEXC');
  cmd            char(32702)  options(*VARSIZE) const;
  cmdLen         packed(15:5) const;
  igc            char(3)      options(*NOPASS) const;
end-pr;

*inLR = *ON;
return;
```
I am running the latest version of VS Code on an up-to-date Windows 11 Pro 64-bit system. The Code for IBM i version is v2.0.2 and the RPGLE extension is v0.20.2.

**Comment by worksofliam** [comment]
0.21.0 is being deployed and the fix for this is included. Thanks!
