### ISSUE TITLE
Free Form Conversion of Subfields Defined with Reserved Words in From-To Length are not Converted Correctly

### ISSUE THREAD

**Issue by BrianGodsend** [halcyon-tech/vscode-rpgle#242]
The data structure subfields may contain reserved words in the From-To Length.  For example, the Program Status Data Structure allows for the reserved words `*STATUS`, `*PROC`, `*PARM`, and `*ROUTINE`.  When these D-specs are converted to **FREE using _Convert to Free Format_, the resulting free form declaration contains "NaN" as the field length and incorrect `pos()` keyword.

Fixed format example:
```RPGLE
     d pgmSts         sds                  qualified
     d  programName      *PROC

       *inLR = *ON;
       return;
```

Annotated results of _Convert to Free Format_:
```RPGLE
**FREE
dcl-ds pgmSts  PSDS qualified;
  // Following line was auto-created and is, obviously, invalid:
  programName    Char(NaN)  Pos(C);
  // The correct line should be like the following:
  programName    *PROC;
end-ds;

*inLR = *ON;
return;
```

For reference, I am running the latest version of VS Code on an up-to-date Windows 11 Pro 64-bit system. The Code for IBM i version is v2.0.2 and the RPGLE extension is v0.20.2.

**Comment by worksofliam** [comment]
Wrong extension. You want vscode-rpgfree.

**Comment by BrianGodsend** [comment]
(Again) Sorry for the incorrect reporting.

Anyone accidentally stumbling on this should note that not only did I report this in the wrong project, but, it is a duplicate of issue number https://github.com/BrianGarland/vscode-rpgfree/issues/62.
