### ISSUE TITLE
Some problem The RPGLE language client server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by ibmiiste** [halcyon-tech/vscode-rpgle#244]
Hi, 

I got this problem (see in the text file).
Do you know what is it? And could you please help me?

[proble rpg server.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12408614/proble.rpg.server.txt)

Regards, 

Olivier.

**Comment by worksofliam** [comment]
Are you using Code for IBM i 2.1.0 and vscode-rpgle 0.21.0?

**Comment by ibmiiste** [comment]
Yes I am.

**Comment by worksofliam** [comment]
@ibmiiste Have you restarted VS Code since updating the extensions?

**Comment by ibmiiste** [comment]
Yes I have, several times.

**Comment by ibmiiste** [comment]
You will find it in the text file:

[RPG crash log.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12409698/RPG.crash.log.txt)

**Comment by worksofliam** [comment]
I have managed to recreate it - looking into it.

**Comment by worksofliam** [comment]
@ibmiiste I found the issue. As of 0.21.0, we finally added include/copy member resolving, but since your source was local and you weren't connected it was just crashing. 0.21.1 will fix this issue.

**Comment by ibmiiste** [comment]
Great job! Thanks!
