### ISSUE TITLE
RPGLE Language client failed now no more functionality from extension.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#246]
I just had the RPGLE Language client fail (sorry I don't have logs for the error).  Once it fails nothing in the extension seems to function.  

Is there a VSCode method of restarting without completing restarting the VSCode session?

**Comment by worksofliam** [comment]
No. Requires a full restart I'm afraid. I should change that.

**Comment by m-tyler** [comment]
I have seen similar error logs as in #244.

**Comment by worksofliam** [comment]
@m-tyler are you able to share them?

**Comment by m-tyler** [comment]
Okay here is a log. It happened whilst opening a member.
[RPGLE_issue_246.txt](https://github.com/halcyon-tech/vscode-rpgle/files/12420869/RPGLE_issue_246.txt)

**Comment by m-tyler** [comment]
Yes.
Yes.

**Comment by worksofliam** [comment]
@m-tyler How large is this code? 

You don't have the share the entire file, but any chance you can share solely the `copy` and `include` directives?

**Comment by m-tyler** [comment]
Give me a little time to get those to you.  I needed to restart VSCode and now its not erroring on the source member I thought it was before.   I might have opened another before the one I linked to the RPGLE language server error. 

I need to try to recreate the problem.

**Comment by m-tyler** [comment]
More information.  I included other output channels.
[RPGLE_issue_246-2.md](https://github.com/halcyon-tech/vscode-rpgle/files/12421413/RPGLE_issue_246-2.md)

**Comment by m-tyler** [comment]
Also, I noticed the section like `for f in ...; do if [ -f $f ]; then echo $f; break; fi; done`.
The follow is the results from QP2TERM and QSHELL.
```
 > for f in /QSYS.LIB/PGMT.LIB/QCPYSRC.FILE/APIERRORDS.MBR; do if [ -f $f ]; then echo $f; break; fi; done         
   $                                                                                                               
 > for f in /QSYS.LIB/WFISRC.LIB/QCPYSRC.FILE/APIERRORDS.MBR; do if [ -f $f ]; then echo $f; break; fi; done       
   $                                                                                                               
 > for f in /WIASP/QSYS.LIB/WFISRC.LIB/QCPYSRC.FILE/APIERRORDS.MBR; do if [ -f $f ]; then echo $f; break; fi; done 
   /WIASP/QSYS.LIB/WFISRC.LIB/QCPYSRC.FILE/APIERRORDS.MBR                                                          
   $                                                                                                               
```
The only one that succeeds is the one with the WIASP reference.

**Comment by m-tyler** [comment]
For your consideration, this statement might be a little slower to complete than the shell code but it far more accurate.

```
;select * from SYSPARTITIONSTAT
where 
( 1=2
or TABLE_NAME = '${SRCFILE}' and TABLE_PARTITION = '${SRCMEMBER}' // Repeat this line for each distinct FILE/MEMBER combo
) 
and TABLE_SCHEMA in ( ${LIBLIST} )

```

**Comment by worksofliam** [comment]
@m-tyler thanks! You're using an ASP.. I will test with that further.

It's actually a good idea to switch to using SQL (thanks for your lovely example).. I will consider it this week.

Nonetheless, it shouldn't be crashing. I will look into improving the handling.

**Comment by worksofliam** [comment]
That would indicate it's not on your library list?

**Comment by m-tyler** [comment]
The member is on the *LIBL but not in the source file found first which is in LIB PGMT. 

QCPYSYC in my *LIBL (obtained by this SQL `select * from QSYS/QADBXREF XR inner join QSYS2.LIBRARY_LIST_INFO LL on LL.SYSTEM_SCHEMA_NAME = XR.DBXLIB where DBXFIL = 'QCPYSRC' order by LL.ORDINAL_POSITION`)

| DBXFIL	| DBXLIB |
| --| -- |
| QCPYSRC   	| PGMT      |
| QCPYSRC   	| WFIMODULES|
| QCPYSRC   	| WSBINTG   |
| QCPYSRC   	| WSBQUAL  | 
| QCPYSRC   	| WSBSRC    |
| QCPYSRC   	| DEVQUAL  | 
| QCPYSRC   	| DTSINTG   |
| QCPYSRC   	| DTSQUAL  | 
| QCPYSRC   	| DTSUSER   |
| QCPYSRC   	| DTSCNTRL | 
| QCPYSRC   	| WFIINTG   |
| QCPYSRC   	| WFIQUAL  | 
| QCPYSRC   	| WFIOBJ    |
| QCPYSRC   	| WFISRC    |

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/66c76c03-1950-4147-a395-4045fd6cd227)

**Comment by m-tyler** [comment]
This SQL is the most accurate I can think of but it performs poorly the first few times.  After about 3-5 quick executions it responds very fast. 

```
;select * from QSYS2.SYSPARTITIONSTAT PS
inner join QSYS2.LIBRARY_LIST_INFO LL on LL.SYSTEM_SCHEMA_NAME= PS.SYSTEM_TABLE_SCHEMA and LL."TYPE"='USER'
where 
( 
1=2
or TABLE_NAME = '${SRCFILE}' and TABLE_PARTITION = '${SRCMEMBER}' -- Repeat this line for each distinct FILE/MEMBER combo
) 
order by LL.ORDINAL_POSITION
limit 1
```
There must be another tool IBM uses in RDi to search for a member as I can quick open this member in RDi without needing to supply the specific library and it finds the one highest up on the *LIBL. 

In one other post I had posted the idea about performing a ghost compile just to get the event file member references but the flaw in that idea is the event file is created in the library of the compiled object.  This might mean creating the ghost object in ILEDITOR then removing the object.

**Comment by worksofliam** [comment]
How are we not getting the same results with that CL?

I have it scanning the library list pretty well and even have test cases for it.

**Comment by m-tyler** [comment]
BTW, we are at 7.5, I wonder if there is a change to the command then.

**Comment by worksofliam** [comment]
I wonder if `Channel open failure: open failed` is happen due to the sheer amount of requests being sent to the server.

**Comment by m-tyler** [comment]
Maybe, there needs to be a `resolveMembers` that accepts a list of members as well as the library list.

**Comment by worksofliam** [comment]
@m-tyler The likeliness of that happening in the short term is low. I just tested with a member that had 20 or so includes and was not able to recreate this issue.

**Comment by m-tyler** [comment]
I can wait for that update as I recreate an situation where the language server is crashing.   It seems to be only when you open several members from the filter, quickly. 

If I reload VSC using the reload command, the product reconnects and processes each open member at a different pace, the language server does not crash.  If I open the same members more slowly, say double click, wait for outline to populate, open another, repeat, the language server does not crash. 

With members open, reload VSC, open filter where you originally selected to open members, double click on same members quickly and the language server errors or crashes. 

I will attempt to focus on reducing my open members at one time and how quickly I open them to reduce the number of SSH connections made for cross referencing.

**Comment by worksofliam** [comment]
Ok, that I can recreate. I can add better handlers for this.

<img width="523" alt="image" src="https://github.com/halcyon-tech/vscode-rpgle/assets/3708366/e27c7f02-a5a4-44f1-bd84-9fbfe58c48b4">

**Comment by worksofliam** [comment]
@m-tyler 0.21.2 is being release right now which will hold back the spamming of requests to the server! Added a neat queue system which really (really!) helps things in this area.

**Comment by worksofliam** [comment]
ASPs will be next, but will be another issue. Please close this if/when you're happy that the crash no longer happens.

**Comment by m-tyler** [comment]
You are not going to like me after this.  

[RPGLE_issue_246-3.md](https://github.com/halcyon-tech/vscode-rpgle/files/12432966/RPGLE_issue_246-3.md)

If there are no others reporting this issue then I would suggest putting this on the back burner for a little bit as I know how to keep it from happening from the point of opening members.

The log attached is from the development version (0.21.2) of the extension, not the packaged version (0.21.2) so that the line errors are clearer. 

If I have many (3 or more) open members upon start up and I tab to each one to make it build the outlines, I can get Vs Code to present the error. 


I asked another person about this and one suggestion given was possible firewall restrictions on the number of concurrent connections. 

Thanks for working on this for me.

**Comment by worksofliam** [comment]
Will look into this further.

There are no additional connects. Just one, but many channels (ssh term)

**Comment by worksofliam** [comment]
@m-tyler I am trying really hard to create your scenario by having a bunch of tabs already open when I launch VS Code, but I am having 0 luck. Please try the release version, and then if no luck, I'd love to meet with you to diagnose further. Thank you!

**Comment by m-tyler** [comment]
Version 0.21.3 seems to be solving the issues I have seen.   With an added benefit of showing an odd copy book reference in the RPGLE Langauge server output channel. 

The reference in the output channel
```
Validating file from server: member:/QSYSINC/QRPGLESRC/QWCATTR%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Define%20API%20format..rpgleinc
```
What the production source looks like
![image](https://github.com/halcyon-tech/vscode-rpgle/assets/1353665/04989d5f-2f38-419c-a4a3-c69a07474e5d)
Apparently IBM puts a line length limit in copy book statements.

I saw this issue is resolved for me.

**Comment by m-tyler** [comment]
Try as I might, I cannot get the RPGLE Language server to fail any more.  This last update seems to have fixed the problem reported.  I'll close this now. 

THANKS!  Matt
