### ISSUE TITLE
Code completion + linter

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/vscode-rpgle#25]
Maybe I am doing something wrong. When I do a DO it auto completes, however, the linter is given the wrong indentation on it.

![CleanShot 2021-12-06 at 09 04 10](https://user-images.githubusercontent.com/37787504/144869666-731432e4-6ffd-4077-85b3-74d990893282.png)
![CleanShot 2021-12-06 at 09 05 35](https://user-images.githubusercontent.com/37787504/144869847-70510bf1-e15e-42f1-a415-eddc51e1e176.png)

**Comment by worksofliam** [comment]
I take it you have the linter enabled in the settings. The errors are correct there.

Do you have an existing rpglint.json file somewhere? Use this command to open up the lint configuration file it is using.

![image](https://user-images.githubusercontent.com/3708366/144870557-aa62253c-1eab-4f7b-a555-6bfb95239d73.png)

**Comment by worksofliam** [comment]
Also, read these notes on the linter: https://github.com/halcyon-tech/vscode-rpgle#linter
