### ISSUE TITLE
RPGLE: Fix all auto-fixable problems not showing

### ISSUE THREAD

**Issue by BlancoConsulting** [halcyon-tech/vscode-rpgle#252]
When I open a **FREE RPGLE source file with the "select language mode" set to RPGLE, the command palette does not show "RPGLE: Fix all auto-fixable problems".

The linter seems to be working because formatting messages appear.

Attached is a screen shot from another user.

![image](https://github.com/halcyon-tech/vscode-rpgle/assets/77461463/295d650d-d16e-4052-93a8-24960dd9b023)

**Comment by worksofliam** [comment]
It was removed a long time ago. You now use 'Format Document'

**Comment by BlancoConsulting** [comment]
Thank you Liam!
