### ISSUE TITLE
Name on end-proc/end-pi

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#27]
A name is optional, but the linter thinks it is a procedure call.  As in lines 6 and 12 below:

![image](https://user-images.githubusercontent.com/67484051/145858937-cf73c4b2-1064-4c85-a880-865b075da9b3.png)

Also the indentation warning on line 10 seems wrong.

Is there are way to turn off  "Expressions must be surrounded by brackets.", as on line 8?  What's the rational of requiring this on a single condition?

**Comment by SJLennon** [comment]
Here's the code:
```
**FREE
ctl-opt debug nomain option(*nodebugio: *srcstmt) ;
dcl-proc BASE36ADD export ;
    dcl-pi BASE36ADD varchar(50);
        PI_Value varchar(50) const; // Input value
    end-pi BASE36ADD;
    dcl-s a char(1);
    if a ='/';
        a=' ';
    endif;
    return a;
end-proc BASE36ADD;

```
And the rpglint.json, which was created 12/09/2021:
```
{
    "BlankStructNamesCheck": true,
    "QualifiedCheck": true,
    "PrototypeCheck": true,
    "ForceOptionalParens": true,
    "NoOCCURS": true,
    "NoSELECTAll": true,
    "UppercaseConstants": true,
    "IncorrectVariableCase": true,
    "RequiresParameter": true,
    "StringLiteralDupe": true,
    "NoSQLJoins": true
}
```

**Comment by worksofliam** [comment]
@SJLennon On your line 10, I would check they are spaces and not tabs (or another character).

![image](https://user-images.githubusercontent.com/3708366/146037966-1fa71dad-ce02-47ee-ae17-a36bcc74d3c2.png)

Otherwise, this is mostly valid - I just need to add not check after the End-X.

**Comment by worksofliam** [comment]
@SJLennon I just release 0.0.11. I also added a unit test case for this! Thanks

**Comment by SJLennon** [comment]
That has fixed the lines 6 and 12 errors.  Thanks.

(The line 10 indention error went away before this fix went in.  A bit of a mystery.   I suppose there might have been a tab there that went away after I saved it and later reopened it.)

@worksofliam
