### ISSUE TITLE
Duplicate id declaration: '#/properties/UppercaseConstants'

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#28]
Don't know if this is significant, but I get the above in the Problem tab when I create a new RPGLINT.JSON.
![image](https://user-images.githubusercontent.com/67484051/146080554-a65a9ffc-b6af-4eb2-9c0e-c9c615b27aba.png)

**Comment by worksofliam** [comment]
Got the same. Looking into it.

**Comment by SJLennon** [comment]
Problem gone.
@worksofliam
