### ISSUE TITLE
Question: Expressions surrounded by brackets

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#30]
Why does an expression with a single condition need to be surrounded by brackets?
For example: 
```
    if a ='/';
        a=' ';
    endif;
```
It makes sense if there is more than one condition, especially if there is and/or logic, for example:
`        if a ='/' or a = '&' and b = ' ';
`

It would make sense in expressions like this but it **doesn't** complain about them:

`    wkDisc = iCost*stdDisc/100;`

Finally, is there an option in RPGLINT.JSON to turn off expression brackets  checking.?

```
{
  "BlankStructNamesCheck": true,
  "QualifiedCheck": true,
  "PrototypeCheck": true,
  "ForceOptionalParens": true,
  "NoOCCURS": true,
  "NoSELECTAll": true,
  "UppercaseConstants": true,
  "IncorrectVariableCase": true,
  "RequiresParameter": true,
  "StringLiteralDupe": true,
  "NoSQLJoins": true
}
```

**Comment by worksofliam** [comment]
This exists to format the language much like other languages, like C, C# or JS/TS, where brackets are required after the `if` or other conditional statement.
