### ISSUE TITLE
Enhancement: Procedures should not access Globals

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#31]
Subtle error can be introduced if a sub procedure accidentally refers to a global definition when it should be referring to a passed parameter or a local variable. 
In the (contrived) code below, there is a typo bug 4 lines from the bottom at  << Error here <<.  StdDsc should really be StdDisc.  The program still compiles and runs, but gives incorrect results in some cases.

It would be neat if Lint could flag use of global value in sub-procedures.

This may be tricky to do. I also note that there is an RFE for the RPG compiler from back in 2016 to address this issue. It has 74 votes but remains an "Uncommitted Candidate".
https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=97164
```
**free
ctl-opt debug  option(*nodebugio: *srcstmt) dftactgrp(*no) actgrp(*caller)
main(Main);
dcl-s STDDSC  packed(5:2) inz(9.0); //from Item Master External  DS
dcl-proc Main;
    dsply %char(CalcDiscount(10000));
    dsply %char(CalcDiscount(1000));
    return;
end-proc;
// New routine replaces field STDDSC in Item Master
dcl-proc CalcDiscount ;
    dcl-pi CalcDiscount packed(7:2);
        iCost packed(7:2) value;
    end-pi;
    dcl-s StdDisc packed(5:2) inz(10);
    dcl-s BigDisc packed(5:2) inz(5);
    dcl-s wkDisc packed(7:2);
    if (iCost >= 10000);
        wkDisc = (iCost*BigDisc)/100;
    else;
        wkDisc = (iCost*StdDsc)/100;  // << Error here <<
    endif;
    return wkDisc;
end-proc;
```

**Comment by worksofliam** [comment]
I just noticed.. this has already been in for a while but doesn't have a unit test. I will create one.

![image](https://user-images.githubusercontent.com/3708366/150695783-bc607557-2b05-483a-87a1-bd30feb333f8.png)
