### ISSUE TITLE
Quick fix for indentation causes lint issue with DCL inside PRocedures

### ISSUE THREAD

**Issue by davidknittle** [halcyon-tech/vscode-rpgle#36]
I used the auto-convert to convert an entire program that was mixed format. the D specs were in column format. After conversion, i used quick fix to fix the LINT indent errors, and the DCL statements _inside_ the procedure all were indented at 0 and cause a LINT error. I moved them to position 4 and the LINT message went away

**Comment by worksofliam** [comment]
@davidknittle Can you share a sample before you do the quickfix so I can recreate the issue?
