### ISSUE TITLE
After conversion to **FREE, quick fix of indent deletes position 1-5

### ISSUE THREAD

**Issue by davidknittle** [halcyon-tech/vscode-rpgle#37]
We use positions 1-5 currently for mod marks, tied to a mod number in the header. when i convert an RPG to **FREE, these marks are just deleted. Would it be possible via a setting or something to move them to the end of the source line as a // comment or something. we are still trying to determine our rules for mod marking in **FREE code, and this is kind of how we are leaning.

**Comment by worksofliam** [comment]
@davidknittle 

> when i convert an RPG to **FREE, these marks are just deleted. Would it be possible via a setting or something to move them to the end of the source line as a // comment or something?

I think you're describing an issue with a different extension.

It might be worth raising an issue on that repo: https://github.com/BrianGarland/vscode-rpgfree

I will close this for now.

Liam
