### ISSUE TITLE
Add ON-EXIT to indentation rules in linter.js

### ISSUE THREAD

**Issue by JamesBrianHill** [halcyon-tech/vscode-rpgle#39]
Requesting the addition of `ON-EXIT` to indentation rules in linter.js.  At the time I'm submitting this request (2022-01-09 @ 12:34pm EST), that would be line 622.

Current:
if ([
            `IF`, `ELSE`, `ELSEIF`, `FOR`, `FOR-EACH`, `DOW`, `DOU`, `MONITOR`, `ON-ERROR`, `BEGSR`, `SELECT`, `WHEN`, `OTHER`, `DCL-PROC`, `DCL-PI`, `DCL-PR`, `DCL-DS`
          ].includes(opcode)) {

Proposed:
if ([
            `IF`, `ELSE`, `ELSEIF`, `FOR`, `FOR-EACH`, `DOW`, `DOU`, `MONITOR`, `ON-ERROR`, `ON-EXIT`, `BEGSR`, `SELECT`, `WHEN`, `OTHER`, `DCL-PROC`, `DCL-PI`, `DCL-PR`, `DCL-DS`
          ].includes(opcode)) {

**Comment by worksofliam** [comment]
@JamesBrianHill 

Feel free to do either of these:

* a PR to add this line. Though a new PR will also require you to make a test case for this too.
* Please share a code snippet that used `ON-EXIT` and I can do the change and create a valid test.

Thanks!
Liam

**Comment by JamesBrianHill** [comment]
Code snippet:

```
//--------------------------------------------------------------------------------------------------
// Append a single quote. This procedure exists to make other code more readable.
//--------------------------------------------------------------------------------------------------
DCL-PROC Q;
  DCL-PI Q VARCHAR(2048);
    in_str VARCHAR(2048) CONST OPTIONS(*TRIM);
  END-PI;

  DCL-C C_QUOTE '''';
  DCL-S is_abend IND INZ(*OFF);
  DCL-S return_str LIKE(in_str);

  return_str = %TRIM(C_QUOTE + in_str + C_QUOTE);
  RETURN return_str;

  ON-EXIT is_abend;
    IF is_abend;
      return_str = 'Liam does great work!';
    ENDIF;
END-PROC Q;
```

**Comment by worksofliam** [comment]
Looking good. Will be out in an upcoming release.

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/148696936-a62e0f0b-b6ec-4376-9000-dc392d9ae9af.png)

**Comment by bmorris1** [comment]
Would those rules always give a warning about ON-EXIT not being indented? If so, I think there should be an option about ON-EXIT.

Me, I think ON-EXIT should be at the same indentation level as DCL-PROC and END-PROC,

**Comment by bmorris1** [comment]
But for sure, code following ON-EXIT should be indented one level higher than ON-EXIT.

**Comment by worksofliam** [comment]
@bmorris1 Maybe so. I actually like the way @JamesBrianHill provided it because it is part of that procedure and my brain easily associates it when the indentation is higher than the end-proc.
