### ISSUE TITLE
Incorrect indentation problem into Select

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-rpgle#40]
Hi,

last update tell me than a comment before a when into a select block give me this error, while last week no, Could you check?

Many thanks.

![image](https://user-images.githubusercontent.com/9719313/148764209-229c402d-7e30-4c93-8655-5019f41666d8.png)

**Comment by worksofliam** [comment]
@pabloto Send me over a code snippet so I can test it please :) Thanks!

**Comment by pabloto** [comment]
> Ah, in the `when` clause. Well technically, the previous `WHEN` block doesn't end until the next one starts - so how do we determine when to change the indentation.

Until last update it don't give indentation error.

**Comment by worksofliam** [comment]
@pabloto That is because it now lints comment indentation! That comment actually belongs to the `when` clause above it.

Clean example:

```
Select
  When (x = 2);
    // Call other program
    callPgm();

  When (x = 5);
    // Write to file
    writeTable();
Endsl;
```

**Comment by worksofliam** [comment]
@pabloto Plan is to make 'comment indentation' a configurable lint option, with `false` by default.
