### ISSUE TITLE
Linter not working

### ISSUE THREAD

**Issue by Code1109** [halcyon-tech/vscode-rpgle#41]
**Describe the bug**
I installed the linter to my VSC and followed the instructions, but is not 'marking' where the errors are happening in a **FREE source and I think it's because the JSON when written into the iSeries is not recognizing the {} like this:

**This is when I open the linter on VSC**
<img width="354" alt="Screen Shot 2022-01-10 at 5 40 23 PM" src="https://user-images.githubusercontent.com/5393171/148857592-feea9391-5b76-4fd1-be87-847c4e034e37.png">

This is how it's seen in the pub400 source file
![Screen Shot 2022-01-10 at 5 40 44 PM](https://user-images.githubusercontent.com/5393171/148858221-afdcdada-2333-4570-ab25-985f147ac7ec.png)

**Environment (please complete the following information):**
 - Extension version 0.3.0 of RPLE language tools
 - IBM i OS version V7R4M0

Could it be that I need to map some values for these chars?

thank you
Ramon Sandoval

**Comment by worksofliam** [comment]
Here is what the setting looks like. It must be enabled.

![image](https://user-images.githubusercontent.com/3708366/148864586-05bd465c-a1e6-4d31-b9e4-9dc0b9389325.png)

**Comment by Code1109** [comment]
Yes, but I do see that mine has 2 check marks one for free RPG and the other one. for fixed format RPG I did uncheck the fixed one and retried but still doesn't work, the json in the iseries still has invalid char instead of the curly brackets
<img width="774" alt="Screen Shot 2022-01-10 at 9 46 26 PM" src="https://user-images.githubusercontent.com/5393171/148878783-b28524bd-6604-4998-955b-4da4800f4491.png">

**Comment by Code1109** [comment]
BTW the VSCODE source file member RPGLINT is a JSON type:
<img width="537" alt="Screen Shot 2022-01-10 at 10 00 53 PM" src="https://user-images.githubusercontent.com/5393171/148879142-e4c14952-2a56-44ac-83e8-e6b08bf286de.png">

**Comment by worksofliam** [comment]
@Code1109 Will you share a snippet of code that it is not working with?

Thanks!

**Comment by Code1109** [comment]
GM @worksofliam here is the snippet, and BTW great YT videos I've been updating myself on VSC with you videos. thank you
<img width="414" alt="Screen Shot 2022-01-11 at 8 32 45 AM" src="https://user-images.githubusercontent.com/5393171/148962548-0fecf6fd-93be-41ef-9ce0-7a8b93504fa8.png">

**Comment by worksofliam** [comment]
@Code1109 As of right now, the linter does not point out incorrect variable names. This is something that might happen in the future. Do indentation errors appear when you use `IF`, etc?

**Comment by Code1109** [comment]
@worksofliam ahhh sorry about that mate, and to confirm yes the indentation, if, constants does 'lint' them...

**Comment by worksofliam** [comment]
@Code1109 No problem! Thanks for using it! 

For the time being, we really are only linting what is available in the lint configuration.

**Comment by Code1109** [comment]
@worksofliam Hi, want to ask you if I can email you some questions about the video 'Code for IBM i: RPGLE with git, make, and lint', thanks, if so please email me your email to peztoro@gmail.com 

1000 thanks!

**Comment by worksofliam** [comment]
Hey @Code1109!

I don't generally post my email here. Your best bet is to reach out to me on LinkedIn or Twitter for any private communication. I can get you my email then!
