### ISSUE TITLE
Publish to Open VSX - like vscode-ibmi...

### ISSUE THREAD

**Issue by chrjorgensen** [halcyon-tech/vscode-rpgle#42]
Hi Liam.

You made the [publishing of Code for IBM i extension to Open VSX work](https://github.com/halcyon-tech/vscode-ibmi/issues/126) - can we have this extension as well? Please? 🥲 

And maybe the other extensions which adds functionality to the Code for IBM i extension?

Best regards,
Christian

**Comment by worksofliam** [comment]
Hey @chrjorgensen yup - I can do that soon :)

**Comment by worksofliam** [comment]
@chrjorgensen Done and done :D

**Comment by chrjorgensen** [comment]
You rock! 👍
