### ISSUE TITLE
Keeping up with Lint configuration options

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#48]
(This is not a complaint--I understand this is an evolving extension.)

I have trouble keeping up with new configuration options. Today I saw someone else's RPGLINT.JSON and discovered he had options I didn't know about.

So I renamed my RPGLINT.JSON to RPGLINTOLD.JSON, restarted VS Code and had it create a new RPGLINT.JSON. Now I can run a compare, see the new options and the one's I have changed.

**Questions:**
 1. Is this the best way to find out about and install new options?  If so, it means I have to reset any that I changed. If I had my druthers, I think I'd like to see new options put in automatically when the RPGLINT.JSON is opened by the extension and a message something like "New Lint options have been added."
2. Short of renaming RPGLINT.JSON, is there a quick way to turn off and on linting?  I think it would be convenient just to be able to turn it off temporarily while dealing with coding errors.  It can be a bit intrusive, because "Clear Diagnostics" doesn't clear lint errors.

Just for grins, here's my compare.  Note that I seem to have one that has disappeared, though that may be something I did.
![image](https://user-images.githubusercontent.com/67484051/151217317-0336f3dc-1259-41c5-bab9-61fc47756631.png)

**Comment by worksofliam** [comment]
@SJLennon Yes, this is a struggle. Right now, the best is to check the [official schema](https://github.com/halcyon-tech/vscode-rpgle/tree/main/src/schemas), but also the `RPGLINT.JSON` can be prompted on and you can see the available options right within VS Code.

E.g. go to add a new prop and you will see the available options.

**Comment by worksofliam** [comment]
@SJLennon Yes, the configuration has been changes so you can disable the linter but keep the content assist enabled.

See the RPGLE language tools settings in the VS Code settings.

**Comment by SJLennon** [comment]
> See the RPGLE language tools settings in the VS Code settings.

That works, but I have to restart VS Code or disconnect and reconnect to make the settings change take effect,

Ideally, it would be nice to be able to toggle linting on or off without having to restart or disconnect.

@worksofliam

**Comment by SJLennon** [comment]
Hovering helps, but...
I'm unclear what SpecificCasing casing is, and hovering doesn't explain it. I'm guessing from something else that I saw that maybe it is intended to require opcodes to be in a specific case. Though that seems extremely tedious to set up if that is the intended use and you wanted, say, all opcodes to be in uppercase.
Anyway, as a guess to test I added 
`"SpecificCasing": [{ "dsply": "DSPLY" }]`
and that simply disables all linting. Take it out and linting comes back. (An empty array does not disable linting.)
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon let me look into this today, though this should likely be in a seperate issue.

**Comment by worksofliam** [comment]
@SJLennon Checked your JSON. You had your schema wrong.

![image](https://user-images.githubusercontent.com/3708366/152858757-0b59f109-22f7-4093-aca6-abd90af24d4c.png)

**Comment by worksofliam** [comment]
I will change the schema later to make it so those errors show up, like this:

![image](https://user-images.githubusercontent.com/3708366/152859011-51de73bc-fa36-420b-897e-969b54d48c43.png)

**Comment by worksofliam** [comment]
@SJLennon FYI I made a new release which will now show the error like above.

**Comment by SJLennon** [comment]
Not wishing to open a can of worms here, but what about casing of  builtin functions, e.g. , %DATE, %FIELDS, %XLATE and the like?

**Comment by worksofliam** [comment]
Specific casing could absolutely be changed to support declare statements and built in functions.
