### ISSUE TITLE
Lint Qualified data-structure

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-rpgle#54]
Hi, 

a simple bug, a likerec Datastructure is implicity qualified, 
so Could you remove the quick fix bug?

Many thanks.

![image](https://user-images.githubusercontent.com/9719313/152176931-e8c5d5ff-d3e8-440d-9655-92f5d34e6885.png)

**Comment by worksofliam** [comment]
@pabloto 

I can get a fix done for this.

Would you mind sharing the code snippet here so I can make a unit test out of it too?

**Comment by pabloto** [comment]
@worksofliam perfect. it works
