### ISSUE TITLE
Have RPGLint Parser ignore continuation lines

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#58]
Continuation lines are source constant text that wrap to additional source lines with either plus(+) or minus(-) character as the last character on the line. 
`MyVar =' A text string that +
wraps to the next line.  But also +
has more wrapped lines in the source+
';`

If this above source is in the main line area, I receive no warning about spacing.  However, if I wrap that section in a control block then the parser wants me to add leading spaces to the code.   I do not want to always insert leading spaces, especially if I happen to add code like the example in several control block levels. 

The recent comment directive '// @rpglint-skip` works well but I need to skip only sections like the above and not the whole code document.

see issue #55 for initial discussion of this topic.

**Comment by worksofliam** [comment]
First step I need to is try to recreate it. Will post back when I gave.

**Comment by m-tyler** [comment]
[TEMP.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/7996683/TEMP.RPGLE.txt)
This version causes the issue I am referencing.

**Comment by worksofliam** [comment]
@m-tyler Thanks you!!

That is actually a valid error. Even if you use +/- extenders, the extended lines' indentation cannot be less than the indentation of the initial line. The point of the linter is to make sure the code is readable. While your code is valid code, it goes again indentation rules

Your example and the fixed example:

![image](https://user-images.githubusercontent.com/3708366/152394701-4dd85b21-e675-4802-bf74-0053e3f60ff0.png)

I am sure you know this, but using a `-` means the leading spaces are not trimmed, and I get the same result as you example when I use `+`:

```
dcl-proc loadSQLStmt;
// begsr loadSQLStmt;

  MySQLStmt1 = ' with-
P+
)';

  MySQLStmt2 = ' with+
  P+
  )';
end-proc;
```

```
EVAL MySQLStmt1
   MYSQLSTMT1 =  withP)
EVAL MySqlStmt2
   MYSQLSTMT2 =  withP)
```
