### ISSUE TITLE
VSCode intermittently slows down after last update (03-FEB-2022)

### ISSUE THREAD

**Issue by SpiderEkb** [halcyon-tech/vscode-rpgle#59]
After the latest RPGLE language tools update, VSCode periodically starts to slow down for a while. 
Usually this is due to changes in significant sections of the code (for example, copy - paste a block of code). If you look in the task manager, you can see that the consumption of processor resources at these moments increases sharply from "low" to "high" and "very high" for about a second - one and a half. It became so uncomfortable to work that I had to temporarily disable this extension.

**Comment by worksofliam** [comment]
I'm sure it's to do with the changes to how we read files. 

@SpiderEkb can you confirm with me again that this is when working with local sources?

**Comment by SpiderEkb** [comment]
> I'm sure it's to do with the changes to how we read files.
> 
> @SpiderEkb can you confirm with me again that this is when working with local sources?

Yes, I work with local sources only.

Initially, two extensions that were updated last were suspect - Code for IBM i (updated 02-Feb-2022) and RPGLE language tools (updated 03-Feb-2022). Disabling one and the second showed that the problem is in the second, the first does not have such a noticeable effect.

**Comment by worksofliam** [comment]
@SpiderEkb 0.5.7 has just been released. Will you have a go with that and let me know how it goes?

0.5.0 had a large change to how files were read and it looks like it needed a tune-up for local files.

**Comment by worksofliam** [comment]
@SpiderEkb Great! I have to release 0.5.8 to solve an issue in our unit tests, so let me know if anything changes.

**Comment by SpiderEkb** [comment]
> @SpiderEkb Great! I have to release 0.5.8 to solve an issue in our unit tests, so let me know if anything changes.

Ok

**Comment by SpiderEkb** [comment]
@worksofliam Unfortunately, the new version (which I updated today) works worse than yesterday - again the same problem with lags

**Comment by worksofliam** [comment]
@SpiderEkb are you able to share a piece of code with me where you see the problem the worst?

I will look into this today.

**Comment by SpiderEkb** [comment]
Weird. Now everything is working fine. I can't figure out what's wrong.
While I close the issue, I'll watch more.
