### ISSUE TITLE
Lint Qualified nested ds

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-rpgle#60]
Hi,

I little bug like #54, if I define a ds like this:

`

Dcl-Ds DsChangingNodeRole Qualified;
  *n   Int(10)      Inz(0);
  *n   VarChar(20)  Inz('Primary Node');
  *n   Int(10)      Inz(1);
  *n   VarChar(20)  Inz('Backup node');
  *n   Int(10)      Inz(-1);
  *n   VarChar(20)  Inz('Replicate Node');
  *n   Int(10)      Inz(-2);
  *n   VarChar(20)  Inz('Changing Node');
  *n   Int(10)      Inz(-3);
  *n   VarChar(20)  Inz('*List');
  *n   Int(10)      Inz(-4);
  *n   VarChar(20)  Inz('Peer Node');
  Dcl-Ds Role Dim(1) Pos(1);
    Values        Int(10);
    Descriotion   VarChar(20);
  End-Ds Role;
End-Ds DsChangingNodeRole;

`
nested array ds is implicity qualified. 

See Nested data structure subfield at:
[https://www.ibm.com/docs/en/i/7.3?topic=statement-free-form-subfield-definition](url)

Many thanks.

**Comment by worksofliam** [comment]
Fix out tonight
