### ISSUE TITLE
Easily Toggle Linting On or Off

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#61]
I think it would be convenient just to be able to turn linting off temporarily while dealing with coding errors. It can be a bit intrusive, because "Clear Diagnostics" doesn't clear lint errors.

The current way is to go to RPGLE Language Tools and uncheck Rpgle Linter Support Enabled. 

But I have to restart VS Code or disconnect and reconnect to make the setting change take effect,

Ideally, it would be nice to be able to toggle linting on or off without having to restart or disconnect.

**Comment by worksofliam** [comment]
Linting is not a toggle option anymore. If `rpglint.json` exists, then it's on - otherwise, it is off.
