### ISSUE TITLE
Add default Casing to Linter

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#65]
It would be nice to specify default casing for various parts of the language. The default options would be:

1. *lower for lower case
2. *upper for upper case
3. *capitalized for the first letter is capitalized

For example, **opcodes**, where I want them to all be lower case, except for dsply and dou, which I want to be uppercase. 
```
"OpcodeCasing": [
    { "opcode": "*defaultcase", "expected": "*lower" },   // expected could be *lower, *upper, *capitalized
    { "opcode": "dsply", "expected": "DSPLY" },   
    { "opcode": "dou", "expected": "DOU" }
 ]
```
( An odd standard, but it is just to demonstrate the flexibility of the approach.  Most people would probably want just the default case.)

Similar functionality for **builtin** functions:
```
    "BuiltinCasing": [
        {"builtin": "*defaultcase", "*default": "*upper"},
        {"builtin": "%parms", "expected": "%parms"},
        {"builtin": "%timestamp", "expected": "%timeStamp"}
    ]
```
(In example, all builtins are to be upper case, except for %parms and %timestamp.)

Similar functionality for **declares**:
```
    "DeclareCasing": [
        {"dcl": "*defaultcase", "*default":"*capitalized"},
        {"dcl": "dcl-proc", "expected": "DCL-PROC"}
    ]
```
(In example, all dcls are to be capitalized, except for dcl-proc which must be in upper case.)

**Comment by SJLennon** [comment]
Ummm.  You know the code, but I'm still of the opinion it would make more sense to have them separate.  
(Nothing is difficult if you don't have to code it yourself 😃 )

**Comment by worksofliam** [comment]
BIFs, `dcl-*` and `end-x` are now supported.

This example you provided:

```
    "BuiltinCasing": [
        {"builtin": "*defaultcase", "*default": "*upper"},
        {"builtin": "%parms", "expected": "%parms"},
        {"builtin": "%timestamp", "expected": "%timeStamp"}
    ]
```

Would be defined like:

```
  "SpecificCasing": [
    {
      "operation": "%parms",
      "expected": "*lower"
    },
    {
      "operation": "%timestamp",
      "expected": "*lower"
    },
    {
      "operation": "*bif",
      "expected": "*upper"
    }
  ]
```

The list order matters here.

![image](https://user-images.githubusercontent.com/3708366/155901848-750cc251-37fd-4ab3-84fd-7d94ebb1d0d1.png)

I did not add support for `* capitalized`. It could be questioned about what this means for certain declarations. E.g. `Dcl-s` vs `Dcl-S`.  `*upper` and `*lower` works expected. I updated the schema so hovering in the `rpglint.json` file shows this.

I only supported `*declare` and `*bif` for now. `*opcode` to come later (perhaps you could make another issue for now.)

Release coming soon.

**Comment by SJLennon** [comment]
@worksofliam Is this support in 0.6.7?  
I ask because I added your example above to my RPGLINT.JSON and it doesn't seem to do anything.  If support is supposed to be in 0.6.7 I can provide more info.

**Comment by worksofliam** [comment]
@SJLennon it sure it!

Feel free to paste your rpglint.json file also.

**Comment by worksofliam** [comment]
Note to self, 0.6.7 tested and the following works:

```
  "SpecificCasing": [
    {
      "operation": "*bif",
      "expected": "*lower"
    }
  ]
```

<img width="876" alt="image" src="https://user-images.githubusercontent.com/3708366/156056426-d2574ab4-a366-40d2-b79c-b614c834e453.png">

**Comment by SJLennon** [comment]
Well, that strange, it seems to be working now for me. I definitely checked earlier that I was on 0.6.7.  Don't know what I was doing wrong, something was odd that I can't explain. Sorry...
I'll create an issue for *opcode tomorrow.
@worksofliam
