### ISSUE TITLE
Sql with CTE and lint

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-rpgle#66]
Hi, 

I have a very complex sqlrpgle that work with json, the LINT give me many errors like this:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/9719313/154118370-56649e52-d80f-4b42-889f-412c7dda9e35.png">

but I didn't do a select * in my final select,  with many json_object and json_array it return to me only one row.

Is it possibile to check it?

Many thanks

**Comment by worksofliam** [comment]
@pabloto Sure. Please send me the full code snippet and i will take a look into it.

**Comment by pabloto** [comment]
Hi @worksofliam ,

here's a sample:

`
**free
Ctl-Opt  DftActGrp(*no)
  ActGrp(*StgMdl)
  StgMdl(*SNGLVL)
  Thread(*Concurrent)
  Option(*NoUnRef :*SrcStmt :*NoDebugIo)
  DatFmt(*Iso) TimFmt(*Iso)
  Debug(*Constants)
  AlwNull(*UsrCtl)
  DftName(TESTJSON)
  Text('Test Select with json table');
// ____________________________________________________________________________
Dcl-Pr DspLongMsg ExtPgm('QUILNGTX');
  Text      Char(16773100) const options(*varsize);
  Length    Int(10)     Const;
  Msgid     Char(7)     Const;
  Qualmsgf  Char(20)    Const;
  ErrorCode Char(32767) options(*varsize);
End-Pr DspLongMsg;

Dcl-Ds ApiError Qualified;
  BytPrv    Int(10) Inz(%Size(ApiError));
  BytAvl    Int(10) Inz(0);
  MsgId     Char(7);
  *n        Char(1);
  MsgDta    Char(128);
End-Ds ApiError;

Dcl-S Json_string     VarChar(10000);

// ___________________________________________________________________________

*Inlr = *On;

Exec Sql
  Set Option Datfmt = *Iso,
             Timfmt = *Iso,
             Closqlcsr = *EndActGrp,
             Commit = *none;

Exec Sql
  With Tempemp As (
    Select *
      From Sample.Employee
  )
  Select Json_Object(
      'employeeList' Value Json_Arrayagg(
        Json_Object(
          'empNumber' Value Empno, 'name' Value Firstnme, 'surname' Value Lastname
        )
      )
  ) into :Json_string
    From Tempemp;   


DspLongMsg(Json_string:%Len(Json_string):'':'':ApiError);

Return;
`

**Comment by worksofliam** [comment]
I would say this is a valid lint. The option is '`SELECT *` is not allowed in Embedded SQL.' and you have used `SELECT *`.

You might be better off disabling it.

**Comment by pabloto** [comment]
> I would say this is a valid lint. The option is '`SELECT *` is not allowed in Embedded SQL.' and you have used `SELECT *`.
> 
> You might be better off disabling it.

Hi @worksofliam, you are wrong, have you try my snippets? It compile and run without any errors.

In this case select * is allowed, the result of my CTE is only one row.
