### ISSUE TITLE
Lint local source

### ISSUE THREAD

**Issue by Justin-E-Taylor** [halcyon-tech/vscode-rpgle#70]
The FAQ seems to say that local source should work.

> Does this work with local projects? Yes! But, your local RPGLE must be the IFS style path on your copy and include directives.

Source members and IFS source lint, but opening an SQLRPGLE source member on my PC does not.  Is there some extra step I have to perform?

TIA

Windows
RPGLE language tools  v0.4.4  **Typo.  s/b v0.6.4**

**Comment by worksofliam** [comment]
Hey @Justin-E-Taylor you should check you have 0.6.4 installed. 0.4 is a bit outdated.

**Comment by worksofliam** [comment]
You will also need to create a .vscode/rpglint.json file. There is a command that can do that for you.

**Comment by Justin-E-Taylor** [comment]
I mistyped the version.  I'm running v0.6.4.

I'm connected to IBMi, and I have my local source file open.  I run **RPGLE: Open RPGLE lint configuration** from the command palette, but it doesn't appear to do anything.  There's no linting in the source.  Where is the JSON file supposed to be created?  There's nothing in the local folder.

Thanks

**Comment by worksofliam** [comment]
@Justin-E-Taylor Do you have a folder open or do you just have a local file open?

**Comment by Justin-E-Taylor** [comment]
Bingo!

I opened just the file.  I opened the folder in VS and now I have linting.

**Comment by worksofliam** [comment]
@Justin-E-Taylor Glad to hear it friend!
