### ISSUE TITLE
Traditional outline view mode

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#73]
Configurable option to make the outline view more 'traditional' and to group like RDi does:

![image (3)](https://user-images.githubusercontent.com/3708366/155756728-abeefbee-b779-466a-a8c0-b944423943b0.png)

![image](https://user-images.githubusercontent.com/3708366/155756537-5321fa90-39db-457e-b3b9-d43e9fa50f7b.png)

**Comment by SJLennon** [comment]
I'm not all that familiar with outline view in VS Code. From what I can tell, it always appears in the side bar, if you have explorer open:
![image](https://user-images.githubusercontent.com/67484051/156201201-d0838713-796a-4c45-bcb4-7805a8ed202e.png)
I think it would be good to have it in its own tab, and become more like what RDi provides.
@worksofliam

**Comment by SJLennon** [comment]
I figured it could be dragged, but was trying to drop it in with the editors.  Now I see it can be dragged to the panel.  Something new learned.

But providing an outline more like RDi would likely be beneficial to those with larger source members.

@worksofliam

**Comment by worksofliam** [comment]
@SJLennon this idea was actually brought to me by someone else (that's how I got the photos!) and I actually think it's going to worked on by someone else (I've been helping them!)

**Comment by worksofliam** [comment]
This is not something we are considering any further.
