### ISSUE TITLE
Intermittent linting

### ISSUE THREAD

**Issue by Justin-E-Taylor** [halcyon-tech/vscode-rpgle#76]
I have a local folder with 3 **free SQLRPGLE source members.  One lints fine.  The second never linted.  The third did at first, but stopped.

How do I determine what's keeping it from linting?

**Comment by worksofliam** [comment]
Huh! There is an RPGLE language tools output channel. You could check there. I may use this as an excuse to log more information to it.

**Comment by worksofliam** [comment]
@Justin-E-Taylor Does the outline view work for each of them? Or does it only work for the one?

**Comment by worksofliam** [comment]
Later today I will add additional logging. In the meantime, feel free to share code here or with me privately and I can also look at those later today.

**Comment by worksofliam** [comment]
@Justin-E-Taylor 0.6.8 is out with additional logging.

**Comment by Justin-E-Taylor** [comment]
The two files that lint load the outline relatively quick.  The source that won't lint takes a very long time, but the outline does load (ofc, it's 2-4x the size of the other source files).  

Here's the message from the RPGLE language tools log:
> Error linting source_file_path_here: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at Function.getErrors (c:\Users\justin\.vscode\extensions\halcyontechltd.vscode-rpgle-0.6.9\dist\extension.js:1:10163)
    at e.refreshDiagnostics (c:\Users\justin\.vscode\extensions\halcyontechltd.vscode-rpgle-0.6.9\dist\extension.js:1:55041)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by worksofliam** [comment]
@Justin-E-Taylor Any way you're able to share that source that's not working with me?

**Comment by Justin-E-Taylor** [comment]
I'm afraid I can't share the source, even privately.  Sorry.

**Comment by worksofliam** [comment]
@Justin-E-Taylor No problem. Your best bet is to try to recreate it in a new source and then pass it on. I am going to close this until then, but please re-open if you recreate it!
