### ISSUE TITLE
Lint option: Error when CTDATA is used on variable definition

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-rpgle#8]
Because CTDATA is ew

**Comment by priceaj** [comment]
+1!

**Comment by bmorris1** [comment]
Ew indeed.

What about DIM(*CTDATA)? It's still somewhat ew, but maybe not as icky as CTDATA which hardcodes the DIM so the ct data has to match.

**Comment by worksofliam** [comment]
@bmorris1 I should add a rule for that too!

**Comment by worksofliam** [comment]
This one is nice 

![image](https://user-images.githubusercontent.com/3708366/147186722-ad96d95a-c04d-480a-a72d-c02f3ea76574.png)

**Comment by worksofliam** [comment]
And covering @bmorris1's example of using `*CTDATA`

![image](https://user-images.githubusercontent.com/3708366/147187546-f3a847f5-6c56-4009-9b25-666f3e2d1263.png)
