### ISSUE TITLE
Indenting Comments in SELECT Block

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#80]
@worksofliam Not sure if this is a bug or a personal preference.  I have code as below.  I want the comment to align with the following WHEN statement, as this makes sense to me.  
Line 58 is in error, because it is apparently wanting it to indent based on the SELECT.
Line 60, even if I move it after the WHEN it is still in error.
Thoughts? Am I missing something?

![image](https://user-images.githubusercontent.com/67484051/159568055-bcc18e3b-4e24-4e04-ba67-2519e846d7f7.png)

**Comment by worksofliam** [comment]
Not a bug. Expected behavior. See #40 and set `PrettyComments` to `false`.

**Comment by SJLennon** [comment]
Ah!  Apparently, I missed seeing that issue...
________________________________
