### ISSUE TITLE
Hover field definitions for packed database fields

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-rpgle#81]
The on-hover field definitions for packed database fields isn't correct.

Database definition:
![image](https://user-images.githubusercontent.com/17951550/160258983-7263a906-0479-4db8-98fa-143c3740d715.png)

RPG program:
![image](https://user-images.githubusercontent.com/17951550/160258990-86f046a2-a111-41c3-bff7-0fdba364741d.png)

The zoned (numeric) database field was ok, and packed variables defined in the program were ok.

**Comment by worksofliam** [comment]
Fix out soon
