### ISSUE TITLE
Receiving error in IBM i Output log 'CPD0074:  Value 'REPORTSQLE' for FILE exceeds 10 characters.'

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#86]
I receive the error `CPD0074:  Value 'REPORTSQLE' for FILE exceeds 10 characters.` because this command is being run, `DSPFFD FILE(*LIBL/REPORTSQLERROR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RREP177272)`.

The problem looks to occur in parser.js -> fetchTables.  

This would be a medium PTY for me but it does prevent to usage of some feature, although I don't know what looking at the output or code. 

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler Are you able to share some f-specs which might be causing this error? That'd be handy. Thanks!

**Comment by worksofliam** [comment]
Fix due out soon

**Comment by m-tyler** [comment]
You closed this issue indicating that a fix is due out soon.  Did that ever make it out yet?  If so I still see the same error in 0.10.2 if not is it planned soon-ish?

If still not I have another issue that is related.  I am getting this error but I am not able to find the source line that might be linked to it, yet.

```system  "DSPFFD FILE(*LIBL/IT      BE) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RIT 243589)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "CPD0048:  List of values not valid for parameter FILE.\nCPD0048:  List of values not valid for parameter OUTFILE.\nCPF0001:  Error found on DSPFFD command."
}
```

**Comment by m-tyler** [comment]
Okay I found the source of the data for that.  Its reading the source array space.  

```
system  "DSPFFD FILE(*LIBL/ITT     BE) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RITT001851)"; if [[ $? -ne 0 ]]; then exit 1; fi
```
![image](https://user-images.githubusercontent.com/1353665/188228247-fcd610e4-b968-4933-b160-f0df380dabc2.png)

The program is a free format `NOT-**FREE`.

**Comment by worksofliam** [comment]
@m-tyler would you mind opening a new issue for this with that example in the bottom?

I think I know the issue but need to create a new test case for it.

**Comment by m-tyler** [comment]
Yep, no problem.
