### ISSUE TITLE
Parsing of copybook members with dots in the name

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#89]
**Describe the bug**
We have a few copybooks that have a dot in the name, DATEUTL.PR and DATEUTL.DS are two of the most used copybook.   I noticed that the log is showing it having trouble opening the member; it's not the correct member name. 

**To Reproduce**
1. Create a member with a dot in the name.
2. Open RPGLE source and add a line for the copybook member.
3. Look at the Code for IBM i log, you may have to close and reopen the RPGLE member.
4. Search if you have to for `SELECT LENGTH(srcdta) as LENGTH FROM ILEDITOR.[yourlib_yoursrcf_yourmbr] limit 1`

**Expected behavior**
Open the members with dots in their names.  

**Screenshots**
![image](https://user-images.githubusercontent.com/1353665/166819980-9e939e02-c130-4874-bc82-92bf386846a1.png)
![image](https://user-images.githubusercontent.com/1353665/166820087-156a2d10-628d-4b96-8120-136488740b8b.png)

**Environment (please complete the following information):**
 - Extension version 1.3.1
 - IBM i OS version 7.3

**Additional context**
I can understand the problem might be scanning for the dot and stopping.  Maybe there is a scan from the right regexp that can be used.   I am wondering if this is a cause of a problem I have been trying to identify for an issue where the outline is not producing for some members.   There are some cases when opening a member with the member that has a dot in its name is the last log entry.

**Comment by worksofliam** [comment]
What a fun bug! I will look into this.

**Comment by worksofliam** [comment]
@m-tyler Any chance you can provide a code sample for this so I can create a unit test for it?

**Comment by m-tyler** [comment]
[#VS Code - Code for IBM i - Log - Case #.txt](https://github.com/halcyon-tech/vscode-rpgle/files/9213556/VS.Code.-.Code.for.IBM.i.-.Log.-.Case.txt)
[VSCCFII89.RPGLE.TXT](https://github.com/halcyon-tech/vscode-rpgle/files/9213560/VSCCFII89.RPGLE.TXT)

A source member that will recreate and the log (with extra stuff) that shows it creating the alias with the wrong name. 

It can be any pattern of dot in the name and the copy member does not have to exist.

**Comment by worksofliam** [comment]
@m-tyler is this still an issue with newer versions of the language extension?

**Comment by m-tyler** [comment]
The member name is parse correctly now.

![image](https://user-images.githubusercontent.com/1353665/203087297-189b739f-9ef5-4295-871e-720be13c9eae.png)
