### ISSUE TITLE
Linter indentation: Conditional statement on multiple lines

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-rpgle#90]
Conditional statements (IF, WHEN) that span multiple lines are marked as invalid indentation:
![image](https://user-images.githubusercontent.com/17951550/168342146-d51ca7f8-c405-4d3b-8ccb-baeb71acda4f.png)

Also, comments that precede the WHEN statement are considered part of the previous block and are marked as invalid:
![image](https://user-images.githubusercontent.com/17951550/168343961-05bc8a8d-45fb-463d-b19c-64160d26221c.png)

Maybe the linter could figure that one out (comments directly preceding WHEN without any blank lines at the same indentation are ok)?    Maybe a new `@rpglint-skip-all` sort of thing so that we don't need to add rpglint-skip before each comment line?

**Comment by worksofliam** [comment]
Regarding comments inside a `when` block. There have been many issues over this and we couldn't come to an agreement. You will want to toggle `PrettyComments` to turn off indentation checks for comments.
