### ISSUE TITLE
Linter Directive: "// @rpglint-skip" failure

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-rpgle#91]
If I have code like this:
![image](https://user-images.githubusercontent.com/67484051/168847393-2015f974-06d7-4a9a-913f-817608c37c50.png)
And I want to ignore the linting in this case because *N data structures cannot be qualified, it throws off subsequent indentation checks:
![image](https://user-images.githubusercontent.com/67484051/168848195-9eb377e4-d7e8-47d2-95a7-08b797f1fd97.png)

Sample code:
```
**free
ctl-opt debug  option(*nodebugio: *srcstmt) dftactgrp(*no) actgrp(*caller)
main(Main);
dcl-s STDDSC  packed(5:2) inz(9.0); //from Item Master External  DS
// @rpglint-skip
dcl-ds *n ;
    cost packed(10:0);
end-ds;
dcl-proc Main;
    dsply %char(CalcDiscount(10000));
    dsply %char(CalcDiscount(1000));
    return;
end-proc;
// New routine replaces field STDDSC in Item Master
dcl-proc CalcDiscount ;
    dcl-pi CalcDiscount packed(7:2);
        iCost packed(7:2) value;
    end-pi;
    dcl-s StdDisc packed(5:2) inz(10);
    dcl-s BigDisc packed(5:2) inz(5);
    dcl-s wkDisc packed(7:2);
    StdDsc = 99;
    if (iCost >= 10000);
        wkDisc = (iCost*BigDisc)/100;
    Else;
        wkDisc = (iCost*STDDSC)/100;  // << Error here <<
    endif;
    Return wkDisc;
end-proc;

```

**Comment by worksofliam** [comment]
Looks like it's skipping the indent changes too. I understand the issue, so basically we want `// @rpglint-skip` to continue checking the indentation changes.

**Comment by SJLennon** [comment]
@worksofliam 
Yes, I think so: // @rpglint-skip would disable all linting on that line except for indention checking.
This is kind of an edge case I turned up when experimenting with linting.

Is there a way to turn off indention checking for a source member?  Like // @rpglint-noindentcheck.

**Comment by worksofliam** [comment]
@SJLennon it is not currently possible to turn off indentation checking for a specific file.

**Comment by SJLennon** [comment]
I **really** like the indentation feature.  

Except when I'm inserting new code because it works faster than I can type of think and before I can get to the ; at the the line it nearly always has lit up the rest of the screen with indentation errors.  But I'm getting used to it...

**Comment by worksofliam** [comment]
Functionality to find definition of export function.

Perhaps an inline hint, or something like that to do the work.

1. https://www.ibm.com/docs/en/i/7.4?topic=services-program-export-import-info-view
2. Find the source path for the object some how?

**Comment by worksofliam** [comment]
New rules have been added today. And it solves this problem.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/3708366/209156290-e8ad119f-1b0c-4e60-99d5-ae9af4a76cd9.png">

<img width="544" alt="image" src="https://user-images.githubusercontent.com/3708366/209156244-6a533037-b5ff-4ee3-a003-46e9d708a5c6.png">
