### ISSUE TITLE
File record format names duplicated in outline

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-rpgle#99]
Using RPGLE language tools v0.7.3 in VS Code 1.69.1. 

The outline now loads the same file record format name on multiple file entries in the outline.
![image](https://user-images.githubusercontent.com/1353665/179067997-a1529265-c4bd-4464-88b6-7cbe0e573b8f.png)
and 
![image](https://user-images.githubusercontent.com/1353665/179068340-2b2cf57e-ab86-497c-8f6f-2ecdb5b03815.png)
![image](https://user-images.githubusercontent.com/1353665/179068610-1a689759-3e96-4ed1-aed6-673f2a3b1f01.png)

(last two images are from the same program but in different libraries)

**Comment by m-tyler** [comment]
So to help out more.   The file XXXPYYYY the format is XXXFYYYY.  For file XXXYYYTB/PF the format is XXXYYYRF.

**Comment by worksofliam** [comment]
@m-tyler The latest release, 0.9.7, changes how record formats are displayed.. we group by file now.

**Comment by m-tyler** [comment]
It mostly works, at least its not the repeated format name.  You can see from this image that MSTPWEEK has the format and fields from the file above it but the one following MSTPWEEK does not.

![image](https://user-images.githubusercontent.com/1353665/184659916-85ac6a47-8bbd-4a4b-9509-d83026d7c3a8.png)

**Comment by m-tyler** [comment]
[TSTVSC001.RPGLE.txt](https://github.com/halcyon-tech/vscode-rpgle/files/9353877/TSTVSC001.RPGLE.txt)

This program source demonstrates the issue with my setup.  It has all the tables listed in the DCL-F's, in the array space, so you only need to copy them to ACS - RSS and run the script.
Then open the member and the outline should appear wrong.  If you look at the tables in the source you can see that it has different column names for all tables.

**Comment by worksofliam** [comment]
@m-tyler That's a great test script. Thank you!

**Comment by m-tyler** [comment]
One more thing, I never noticed until today.  You can see the format names and fields are from the test source I uploaded a few minutes ago.

![image](https://user-images.githubusercontent.com/1353665/184970236-4bd9b483-ca3b-4823-b605-8c6e08145eb6.png)

**Comment by worksofliam** [comment]
Fix coming out tonight. 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/3708366/185020824-e95c0318-7487-413e-a8e7-b97090febfa6.png">

**Comment by m-tyler** [comment]
Whoo Hoo!
Nice!

Thanks for getting this fix done!
There is a small odd quirk that I am placing on VS Code where the outline shows a but odd with programs that were opened before in VS Code but closing and reopening or causing the outline to rebuild seems to get that information to correct itself.

This is an image of a program opened up after the extension update but that was also opened prior to. 
![image](https://user-images.githubusercontent.com/1353665/185171618-5b2a510f-80f2-4562-874c-e4202e553aba.png)


The after image of reloading the outline after reopening the source or triggering the outline to rebuild. 
![image](https://user-images.githubusercontent.com/1353665/185172066-3eb41357-3def-461f-95f6-2ba8f9ce9523.png)

It self resolves so I am not asking for a fix but just noting it here.  I wonder if there is a way to clear the VS Code outline cache?

**Comment by worksofliam** [comment]
The outline cache is something I've been meaning to look into. Thanks for mentioning it.
